import { SupabaseClient } from '@supabase/supabase-js';
import { Result } from '@/src/core/domain/result';
import { ISource } from '@/src/shared/backend/source/domain/repository/source.repository';
import { IMovementRepository } from '../../domain/repository/movement.repository';
import { Movement, MovementAdjustmentKind, MovementType } from '../../domain/movement';

type Raw = { id:string|null; company_id:string; product_id:string; type:MovementType; date:string; period:string; quantity:number|null; unit_cost:number|null; total_cost:number|null; balance_quantity:number|null; reference:string|null; notes:string|null; currency:string|null; currency_cost:number|null; dollar_rate:number|null; discount_type:string|null; discount_value:number|string|null; discount_amount:number|string|null; surcharge_type:string|null; surcharge_value:number|string|null; surcharge_amount:number|string|null; vat_base:number|string|null; sale_price_unit:number|string|null; created_at:string|null };
const n=(v:number|string|null|undefined,d=0)=>v==null||v===''?d:Number(v);
const k=(v:string|null|undefined):MovementAdjustmentKind|null=>v==='monto'||v==='porcentaje'?v:null;

export class SharedMovementRepository implements IMovementRepository {
  constructor(private readonly source:ISource<SupabaseClient>,private readonly tenantId:string){}
  async findByCompany(companyId:string,period?:string):Promise<Result<Movement[]>>{try{let q=this.source.instance.from('shared_inventory_movements').select('*').eq('tenant_id',this.tenantId).eq('company_id',companyId).order('date',{ascending:false});if(period)q=q.eq('period',period);const {data,error}=await q;if(error)return Result.fail(error.message);return Result.success(((data as Raw[])??[]).map(r=>this.map(r)));}catch(e){return Result.fail(e instanceof Error?e.message:'Failed to fetch movements');}}
  async save(m:Movement):Promise<Result<Movement>>{try{const row={id:m.id??'',empresa_id:m.companyId,producto_id:m.productId,tipo:m.type,fecha:m.date,cantidad:m.quantity,costo_unitario:m.unitCost,moneda:m.currency??'B',costo_moneda:m.currencyCost??null,tasa_dolar:m.dollarRate??null,referencia:m.reference,notas:m.notes,descuento_tipo:m.descuentoTipo??'',descuento_valor:m.descuentoValor??'',descuento_monto:m.descuentoMonto??'',recargo_tipo:m.recargoTipo??'',recargo_valor:m.recargoValor??'',recargo_monto:m.recargoMonto??'',base_iva:m.baseIVA??'',precio_venta_unitario:m.precioVentaUnitario??''};const {data,error}=await this.source.instance.rpc('shared_inventory_movement_save',{p_tenant_id:this.tenantId,p_row:row});if(error)return Result.fail(error.message);return Result.success(this.map(data as Raw));}catch(e){return Result.fail(e instanceof Error?e.message:'Failed to save movement');}}
  async delete(id:string):Promise<Result<void>>{try{const {error}=await this.source.instance.from('shared_inventory_movements').delete().eq('tenant_id',this.tenantId).eq('id',id);return error?Result.fail(error.message):Result.success();}catch(e){return Result.fail(e instanceof Error?e.message:'Failed to delete movement');}}
  async updateMeta(id:string,date:string,reference:string,notes:string):Promise<Result<Movement>>{try{const {data,error}=await this.source.instance.from('shared_inventory_movements').update({date,period:date.slice(0,7),reference,notes}).eq('tenant_id',this.tenantId).eq('id',id).select('*').single();if(error)return Result.fail(error.message);return Result.success(this.map(data as Raw));}catch(e){return Result.fail(e instanceof Error?e.message:'Failed to update movement');}}
  async getInboundTotal(companyId:string,period:string):Promise<Result<number>>{const r=await this.findByCompany(companyId,period);if(r.isFailure)return Result.fail(r.getError());const inbound:MovementType[]=['entrada','devolucion_salida','ajuste_positivo'];return Result.success(r.getValue().filter(m=>inbound.includes(m.type)).reduce((s,m)=>s+m.totalCost,0));}
  private map(r:Raw):Movement{return{id:r.id??undefined,companyId:r.company_id,productId:r.product_id,type:r.type,date:r.date,period:r.period,quantity:n(r.quantity),unitCost:n(r.unit_cost),totalCost:n(r.total_cost),balanceQuantity:n(r.balance_quantity),reference:r.reference??'',notes:r.notes??'',currency:r.currency==='D'?'D':'B',currencyCost:r.currency_cost!=null?Number(r.currency_cost):null,dollarRate:r.dollar_rate!=null?Number(r.dollar_rate):null,descuentoTipo:k(r.discount_type),descuentoValor:n(r.discount_value),descuentoMonto:n(r.discount_amount),recargoTipo:k(r.surcharge_type),recargoValor:n(r.surcharge_value),recargoMonto:n(r.surcharge_amount),baseIVA:n(r.vat_base,n(r.total_cost)),precioVentaUnitario:r.sale_price_unit==null||r.sale_price_unit===''?null:Number(r.sale_price_unit),createdAt:r.created_at??undefined};}
}
