import {useEffect,useMemo,useRef,useState,type FormEvent}from"react";
import Chart from"chart.js/auto";
import type{TooltipItem}from"chart.js";
import{Archive,Building2,CircleDollarSign,History,Info,Package,RefreshCw,Save,Tag}from"lucide-react";
import type{NativeProductCategoryDto,NativeProductDetailDto,NativeProductUnitEconomicsDto,NativeUnitOfMeasure}from"@kontave/native-api-contracts";
import{codedErrorFeedback,successFeedback}from"@kontave/client-feedback-application";
import{Button,CurrencyFlag,DatePicker,OptionPicker,Skeleton,StatusBadge,presentFeedback}from"@kontave/ui-dom";
import{runExclusiveMutation}from"./client-interaction";
import type{DesktopInventoryDashboardSnapshot}from"../../shared/desktop-api";

export function ProductDetailPage({companyId,onTitleChange,organizationId,productId,userId}:{readonly companyId:string;readonly onTitleChange?:(title:string)=>void;readonly organizationId:string;readonly productId:string;readonly userId:string}){
 const[product,setProduct]=useState<NativeProductDetailDto>();const[categories,setCategories]=useState<readonly NativeProductCategoryDto[]>([]);const[insights,setInsights]=useState<NativeProductUnitEconomicsDto>();const[presentation,setPresentation]=useState<DesktopInventoryDashboardSnapshot>();const[displayCurrency,setDisplayCurrency]=useState("VES");const[granularity,setGranularity]=useState<"day"|"week"|"month">("month");const[reload,setReload]=useState(0);
 const period=useMemo(()=>{const to=new Date().toISOString().slice(0,10),from=new Date();from.setUTCFullYear(from.getUTCFullYear()-1);return{from:from.toISOString().slice(0,10),to}},[]);
 useEffect(()=>{let active=true;void Promise.all([window.kontave.products.get(organizationId,companyId,productId),window.kontave.products.categories(organizationId,companyId,"active"),window.kontave.products.unitEconomics(organizationId,companyId,productId,{...period,granularity})]).then(([detail,categoryList,economics])=>{if(!active)return;if(detail.ok)setProduct(detail.value);else failure(detail.error);if(categoryList.ok)setCategories(categoryList.value);else failure(categoryList.error);if(economics.ok)setInsights(economics.value);else failure(economics.error);});return()=>{active=false}},[companyId,granularity,organizationId,period,productId,reload]);
 useEffect(()=>{let active=true;void window.kontave.inventory.getDashboard(userId,organizationId,companyId).then(result=>{if(!active||!result.ok)return;setPresentation(result.value);setDisplayCurrency(result.value.operationContext.presentationCurrency)});return()=>{active=false}},[companyId,organizationId,userId]);
 useEffect(()=>{if(product?.name)onTitleChange?.(product.name)},[onTitleChange,product?.name]);
 if(!product)return <DetailSkeleton/>;const canUpdate=true;
 async function reloadProduct(){const result=await window.kontave.products.get(organizationId,companyId,productId);if(result.ok)setProduct(result.value);else failure(result.error)}
 async function status(){if(!product)return;const current=product;const result=await runExclusiveMutation(current.status==="active"?"Desactivando producto":"Reactivando producto",()=>window.kontave.products.setStatus(organizationId,companyId,current.id,current.status!=="active",current.version));if(result.ok){await reloadProduct();presentFeedback.execute(successFeedback(current.status==="active"?"Producto desactivado.":"Producto reactivado."))}else failure(result.error,reloadProduct)}
 return <section className="product-page"><header className="product-page__hero"><div><span>Producto</span><h2>{product.name}</h2><p>{product.sku||"Sin SKU"}</p></div><div className="product-page__hero-actions"><Button size="sm" appearance="outline" intent="neutral" iconOnly aria-label="Actualizar producto" title="Actualizar producto" onClick={()=>setReload(v=>v+1)}><RefreshCw/></Button>{canUpdate?<Button size="sm" appearance="outline" intent={product.status==="active"?"danger":"primary"} onClick={()=>void status()}><Archive/>{product.status==="active"?"Desactivar":"Reactivar"}</Button>:null}</div></header>
 <div className="product-page__stats"><Stat icon={<Package/>} label="Existencia" value={product.inventory?`${decimal(product.inventory.onHand.quantity)} ${unit(product.inventory.onHand.unit)}`:"—"}/><Stat icon={<CircleDollarSign/>} label="Costo promedio" value={product.inventory?money(product.inventory.valuation.unitCost):"—"}/><Stat icon={<Tag/>} label="Precio de venta" value={pricing(product)}/><Stat icon={<Building2/>} label="Categoría" value={product.category?.name??"Sin categoría"}/></div>
 <nav className="product-page__tabs" aria-label="Secciones del producto"><a href="#product-general"><Info/>Información general</a><a href="#product-pricing"><Tag/>Precios</a><a href="#product-history"><History/>Historial</a></nav>
 <div id="product-general" className="product-page__detail-grid"><IdentityForm product={product} categories={categories} disabled={!canUpdate} organizationId={organizationId} companyId={companyId} onSaved={reloadProduct}/><aside className="product-page__summary"><h3>Resumen del producto</h3><dl><div><dt>Estado</dt><dd><StatusBadge intent={product.status==="active"?"success":"neutral"}>{product.status==="active"?"Activo":"Inactivo"}</StatusBadge></dd></div><div><dt>Última actualización</dt><dd>{dateTime(product.updatedAt)}</dd></div><div><dt>Versión</dt><dd>{product.version}</dd></div></dl><p>Mantén la información actualizada para mejorar el control del inventario.</p></aside></div>
 {product.capabilities.salePricing?<div id="product-pricing"><PricingForm product={product} disabled={!canUpdate} organizationId={organizationId} companyId={companyId} onSaved={reloadProduct}/></div>:null}
 {product.capabilities.vatConfiguration&&product.taxation?<TaxForm product={product} disabled={!canUpdate} organizationId={organizationId} companyId={companyId} onSaved={reloadProduct}/>:null}
 <div id="product-history"><Insights value={insights} granularity={granularity} onGranularity={setGranularity} presentation={presentation} displayCurrency={displayCurrency} onCurrency={setDisplayCurrency}/></div>
 </section>;
}
function IdentityForm({categories,companyId,disabled,onSaved,organizationId,product}:{readonly categories:readonly NativeProductCategoryDto[];readonly companyId:string;readonly disabled:boolean;readonly onSaved:()=>Promise<void>;readonly organizationId:string;readonly product:NativeProductDetailDto}){const[name,setName]=useState(product.name),[sku,setSku]=useState(product.sku),[description,setDescription]=useState(product.description??""),[categoryId,setCategoryId]=useState(product.category?.id??""),[baseUnit,setBaseUnit]=useState(product.baseUnit),[barcodes,setBarcodes]=useState(product.barcodes.join(", "));async function submit(e:FormEvent){e.preventDefault();const result=await runExclusiveMutation("Guardando producto",()=>window.kontave.products.update(organizationId,companyId,product.id,{name:name.trim(),sku:sku.trim(),description:description.trim()||null,categoryId:categoryId||null,baseUnit,barcodes:barcodes.split(",").map(v=>v.trim()).filter(Boolean),expectedVersion:product.version}));if(result.ok){await onSaved();presentFeedback.execute(successFeedback("Producto actualizado."))}else failure(result.error,onSaved)}return <Card title="Identidad y clasificación"><form className="product-page__form" onSubmit={e=>void submit(e)}><Field label="Nombre"><input disabled={disabled} value={name} onChange={e=>setName(e.target.value)}/></Field><Field label="SKU"><input disabled={disabled} value={sku} onChange={e=>setSku(e.target.value)}/></Field><Field label="Códigos de barras"><input disabled={disabled} value={barcodes} onChange={e=>setBarcodes(e.target.value)}/></Field><Field label="Departamento"><OptionPicker label="Departamento" value={categoryId} options={[{value:"",label:"Sin departamento"},...categories.map(category=>({value:category.id,label:category.name}))]} onChange={setCategoryId}/></Field><Field label="Unidad base"><OptionPicker label="Unidad base" value={baseUnit} options={UNITS.map(value=>({value,label:unit(value)}))} onChange={setBaseUnit}/></Field><Field label="Descripción"><textarea disabled={disabled} value={description} onChange={e=>setDescription(e.target.value)}/></Field>{!disabled?<footer><Button size="sm" type="submit"><Save/>Guardar cambios</Button></footer>:null}</form></Card>}
function PricingForm({companyId,disabled,onSaved,organizationId,product}:{readonly companyId:string;readonly disabled:boolean;readonly onSaved:()=>Promise<void>;readonly organizationId:string;readonly product:NativeProductDetailDto}){const current=product.salePricing;const[mode,setMode]=useState<"none"|"fixed"|"markup">(current?.policy?.mode??"none"),[amount,setAmount]=useState(current?.policy?(current.policy.mode==="fixed"?current.policy.amount:current.policy.percentage):""),[currency,setCurrency]=useState(current?.policy?.currency??"VES");async function submit(e:FormEvent){e.preventDefault();if(!current)return;const policy=mode==="none"?null:mode==="fixed"?{mode,amount,currency}as const:{mode,percentage:amount,currency}as const;const result=await runExclusiveMutation("Guardando precio",()=>window.kontave.products.updateSalePricing(organizationId,companyId,product.id,{policy,expectedVersion:current.version}));if(result.ok){await onSaved();presentFeedback.execute(successFeedback("Precio actualizado."))}else failure(result.error,onSaved)}return <Card title="Precio de venta"><form className="product-page__form product-page__form--compact" onSubmit={e=>void submit(e)}><Field label="Política"><OptionPicker label="Política" value={mode} options={[{value:"none",label:"Sin precio"},{value:"fixed",label:"Monto fijo"},{value:"markup",label:"Porcentaje sobre costo"}]} onChange={setMode}/></Field>{mode!=="none"?<><Field label={mode==="fixed"?"Monto":"Porcentaje"}><input inputMode="decimal" disabled={disabled} value={amount} onChange={e=>setAmount(e.target.value)}/></Field><Field label="Moneda"><input disabled={disabled} value={currency} onChange={e=>setCurrency(e.target.value.toUpperCase())}/></Field></>:null}{!disabled?<footer><Button size="sm" type="submit">Guardar precio</Button></footer>:null}</form></Card>}
function TaxForm({companyId,disabled,onSaved,organizationId,product}:{readonly companyId:string;readonly disabled:boolean;readonly onSaved:()=>Promise<void>;readonly organizationId:string;readonly product:NativeProductDetailDto}){const tax=product.taxation!;const[treatment,setTreatment]=useState(tax.treatment),[effectiveFrom,setEffectiveFrom]=useState(tax.effectiveFrom),[legalBasis,setLegalBasis]=useState(tax.legalBasis);async function submit(e:FormEvent){e.preventDefault();const result=await runExclusiveMutation("Guardando IVA",()=>window.kontave.products.updateTaxation(organizationId,companyId,product.id,{treatment,effectiveFrom,legalBasis,expectedVersion:tax.version}));if(result.ok){await onSaved();presentFeedback.execute(successFeedback("Tratamiento tributario actualizado."))}else failure(result.error,onSaved)}return <Card title="IVA"><form className="product-page__form product-page__form--compact" onSubmit={e=>void submit(e)}><Field label="Tratamiento"><OptionPicker label="Tratamiento" value={treatment} options={[{value:"taxed",label:"Gravado"},{value:"exempt",label:"Exento"},{value:"exonerated",label:"Exonerado"},{value:"not_subject",label:"No sujeto"}]} onChange={setTreatment}/></Field><Field label="Vigente desde"><DatePicker label="Vigente desde" value={effectiveFrom} onChange={setEffectiveFrom}/></Field><Field label="Base legal"><input disabled={disabled} value={legalBasis} onChange={e=>setLegalBasis(e.target.value)}/></Field>{!disabled?<footer><Button size="sm" type="submit">Guardar IVA</Button></footer>:null}</form></Card>}
function Insights({displayCurrency,granularity,onCurrency,onGranularity,presentation,value}:{readonly displayCurrency:string;readonly granularity:"day"|"week"|"month";readonly onCurrency:(value:string)=>void;readonly onGranularity:(v:"day"|"week"|"month")=>void;readonly presentation:DesktopInventoryDashboardSnapshot|undefined;readonly value:NativeProductUnitEconomicsDto|undefined}){const rates=presentation?.exchangeRates.rates??[],rate=rates.find(item=>item.baseCurrency===displayCurrency)??null,currencies=[{value:"VES",label:"Bolívar venezolano",description:"Moneda base",icon:<CurrencyFlag currency="VES"/>},...rates.map(item=>({value:item.baseCurrency,label:currencyName(item.baseCurrency),description:`1 ${item.baseCurrency} = ${decimal(item.value)} VES`,icon:<CurrencyFlag currency={item.baseCurrency}/>}))],convert=(amount:string)=>displayCurrency==="VES"?Number(amount):rate&&Number(rate.value)>0?Number(amount)/Number(rate.value):Number(amount);return <Card title="Historial de compras y precios" action={<div className="product-chart__controls"><OptionPicker label="Moneda" value={displayCurrency} options={currencies} searchable searchPlaceholder="Buscar moneda..." onChange={onCurrency}/><OptionPicker label="Agrupación" value={granularity} options={[{value:"day",label:"Día"},{value:"week",label:"Semana"},{value:"month",label:"Mes"}]} onChange={onGranularity}/></div>}>{value?<><p className="product-chart__description">Compara el costo de compra y el precio unitario efectivamente facturado. Los valores originales permanecen en VES.</p>{value.latestAcquisition?<div className="product-chart__summary"><StatText label="Última compra" value={chartDate(value.latestAcquisition.effectiveDate)}/><StatText label="Costo original" value={`${decimal(value.latestAcquisition.sourceUnitAmount.amount)} ${value.latestAcquisition.sourceUnitAmount.currency}`}/><StatText label={`Costo en ${displayCurrency}`} value={formatCurrency(convert(value.latestAcquisition.unitAmount.amount),displayCurrency)}/></div>:null}<div className="product-chart-meta"><span>Compras confirmadas <strong>{value.coverage.confirmedAcquisitions}</strong></span><span>Ventas confirmadas <strong>{value.coverage.confirmedSales}</strong></span>{value.coverage.legacyRecordedOutboundPrices?<span>Precios heredados <strong>{value.coverage.legacyRecordedOutboundPrices}</strong></span>:null}</div><ComparisonChart value={value} currency={displayCurrency} convert={convert}/></>:<Skeleton variant="rectangle" width="100%" height={280}/>}</Card>}
function ComparisonChart({convert,currency,value}:{readonly convert:(amount:string)=>number;readonly currency:string;readonly value:NativeProductUnitEconomicsDto}){
 const canvasRef=useRef<HTMLCanvasElement|null>(null),chartRef=useRef<Chart|null>(null);
 useEffect(()=>{if(!canvasRef.current||value.points.length===0)return;chartRef.current?.destroy();const purchase=value.points.map(point=>point.acquisition?convert(point.acquisition.weightedAverageUnitAmount.amount):null),sales=value.points.map(point=>point.realizedSale?convert(point.realizedSale.weightedAverageUnitAmount.amount):null);chartRef.current=new Chart(canvasRef.current,{type:"line",data:{labels:value.points.map(point=>chartDate(point.bucketStart)),datasets:[{label:"Costo de adquisición",data:purchase,borderColor:"#e74613",backgroundColor:"#e74613",pointRadius:4,pointHoverRadius:6,borderWidth:2.5,tension:.2,spanGaps:false},{label:"Precio facturado",data:sales,borderColor:"#16a34a",backgroundColor:"#16a34a",pointRadius:4,pointHoverRadius:6,borderWidth:2.5,tension:.2,spanGaps:false}]},options:{responsive:true,maintainAspectRatio:false,interaction:{mode:"index",intersect:false},plugins:{legend:{display:true,position:"bottom",labels:{usePointStyle:true,boxWidth:7,padding:18,font:{family:"monospace",size:11}}},tooltip:{callbacks:{label:(context:TooltipItem<"line">)=>`${context.dataset.label}: ${formatCurrency(Number(context.parsed.y),currency)}`}}},scales:{x:{grid:{display:false},ticks:{maxTicksLimit:8,font:{family:"monospace",size:10}}},y:{beginAtZero:false,grid:{color:"rgba(100, 116, 139, 0.18)"},ticks:{callback:tick=>`${currency} ${Number(tick).toLocaleString("es-VE",{maximumFractionDigits:2})}`,font:{family:"monospace",size:10}}}}}});return()=>{chartRef.current?.destroy();chartRef.current=null}},[convert,currency,value]);
 if(value.points.length===0)return <div className="product-chart__empty">No hay compras o ventas confirmadas para graficar.</div>;
 return <div className="product-chart product-chart--canvas"><canvas ref={canvasRef}/></div>
}
function Card({action,children,title}:{readonly action?:React.ReactNode;readonly children:React.ReactNode;readonly title:string}){return <section className="product-page__card"><header><h3>{title}</h3>{action}</header>{children}</section>};function Field({children,label}:{readonly children:React.ReactNode;readonly label:string}){return <label><span>{label}</span>{children}</label>};function Stat({icon,label,value}:{readonly icon:React.ReactNode;readonly label:string;readonly value:string}){return <article><i aria-hidden="true">{icon}</i><div><span>{label}</span><strong>{value}</strong></div></article>};function DetailSkeleton(){return <section className="product-page"><Skeleton variant="rectangle" width="100%" height={110}/><Skeleton variant="rectangle" width="100%" height={300}/></section>};function failure(error:{readonly code:string;readonly message:string;readonly requestId:string|null},retry?:()=>void|Promise<void>){presentFeedback.execute(codedErrorFeedback({code:error.requestId??error.code,message:error.code.includes("VERSION_CONFLICT")?"Esta sección cambió en otro cliente. Recargamos sus datos para que puedas revisar los cambios.":error.message,deduplicationKey:`product-detail-${error.requestId??error.code}`}));if(error.code.includes("VERSION_CONFLICT"))void retry?.()}
function chartDate(value:string){return new Intl.DateTimeFormat("es-VE",{day:"2-digit",month:"short",timeZone:"UTC"}).format(new Date(`${value}T00:00:00Z`)).replace(".","")}
function StatText({label,value}:{readonly label:string;readonly value:string}){return <div><span>{label}</span><strong>{value}</strong></div>}
function dateTime(value:string){return new Intl.DateTimeFormat("es-VE",{dateStyle:"medium",timeStyle:"short"}).format(new Date(value))}
function currencyName(code:string){return new Intl.DisplayNames(["es-VE"],{type:"currency"}).of(code)??code}function formatCurrency(value:number,currency:string){return new Intl.NumberFormat("es-VE",{style:"currency",currency,maximumFractionDigits:2}).format(value)}
function pricing(p:NativeProductDetailDto){const policy=p.salePricing?.policy;if(!policy)return"Sin configurar";return policy.mode==="fixed"?`${decimal(policy.amount)} ${policy.currency}`:`${decimal(policy.percentage)} % sobre costo`};function money(v:string){return`${decimal(v)} VES`};function decimal(v:string){const[i="0",f=""]=v.split(".");return`${i.replace(/\B(?=(\d{3})+(?!\d))/g,".")}${f.replace(/0+$/,"")?`,${f.replace(/0+$/,'')}`:""}`};const UNITS:readonly NativeUnitOfMeasure[]=["each","kilogram","gram","meter","square_meter","cubic_meter","liter","gallon","box","roll","package"];function unit(v:NativeUnitOfMeasure){return({each:"Unidad",kilogram:"kg",gram:"g",meter:"m",square_meter:"m²",cubic_meter:"m³",liter:"L",gallon:"gal",box:"Caja",roll:"Rollo",package:"Paquete"})[v]}
