import { useEffect, useMemo, useRef, useState, type FormEvent } from "react";
import { Archive, ArrowDown, ArrowUp, ChevronRight, Folders, Plus, RefreshCw, Search, X } from "lucide-react";
import type { NativeProductCategoryOverviewDto, NativeProductCategoryOverviewItemDto, NativeProductDto } from "@kontave/native-api-contracts";
import { codedErrorFeedback, successFeedback } from "@kontave/client-feedback-application";
import { Button, OptionPicker, Skeleton, StatusBadge, presentFeedback } from "@kontave/ui-dom";
import type { DesktopProductCategoryOverviewQuery } from "../../shared/desktop-api.js";
import { runExclusiveMutation } from "./client-interaction.js";

interface ProductCategoriesViewProps { readonly organizationId:string;readonly companyId:string }
type CategoryStatus="active"|"inactive"|"all";
type CategorySort="name"|"products"|"updatedAt";

export function ProductCategoriesView({companyId,organizationId}:ProductCategoriesViewProps){
  const [page,setPage]=useState<NativeProductCategoryOverviewDto>();
  const [permissions,setPermissions]=useState<readonly string[]>([]);
  const [search,setSearch]=useState("");
  const [debouncedSearch,setDebouncedSearch]=useState("");
  const [status,setStatus]=useState<CategoryStatus>("all");
  const [sort,setSort]=useState<CategorySort>("name");
  const [direction,setDirection]=useState<"asc"|"desc">("asc");
  const [cursor,setCursor]=useState<string>();
  const [loading,setLoading]=useState(true);
  const [refreshing,setRefreshing]=useState(false);
  const [reload,setReload]=useState(0);
  const [selectedId,setSelectedId]=useState<string>();
  const [creating,setCreating]=useState(false);
  const sequence=useRef(0);
  useEffect(()=>{const timer=window.setTimeout(()=>{setCursor(undefined);setDebouncedSearch(search.trim())},300);return()=>window.clearTimeout(timer)},[search]);
  const query=useMemo<DesktopProductCategoryOverviewQuery>(()=>({search:debouncedSearch,status,sort,direction,limit:25,...(cursor?{cursor}:{})}),[cursor,debouncedSearch,direction,sort,status]);
  useEffect(()=>{let active=true;const current=++sequence.current;void Promise.all([window.kontave.products.categoryOverview(organizationId,companyId,query),window.kontave.products.permissions(organizationId)]).then(([overview,access])=>{if(!active||current!==sequence.current)return;if(overview.ok)setPage(previous=>query.cursor&&previous?{...overview.value,items:[...previous.items,...overview.value.items]}:overview.value);else presentCategoryFailure(overview.error);if(access.ok)setPermissions(access.value);else presentCategoryFailure(access.error);setLoading(false);setRefreshing(false)});return()=>{active=false}},[companyId,organizationId,query,reload]);
  function refresh(){setRefreshing(true);setCursor(undefined);setReload(value=>value+1)}
  if(loading&&!page)return <CategorySkeleton/>;
  return <section className="products-page category-page">
    <header className="products-page__heading"><div><h2>Departamentos</h2><p>Categorías para clasificar los productos de la empresa seleccionada.</p></div><div><Button appearance="unstyled" aria-label="Actualizar departamentos" onClick={refresh}><RefreshCw className={refreshing?"is-spinning":undefined}/></Button>{permissions.includes("inventory.create")?<Button onClick={()=>setCreating(true)}><Plus/>Nuevo departamento</Button>:null}</div></header>
    {page?<CategorySummary summary={page.summary} total={page.total}/>:null}
    <div className="products-toolbar category-toolbar"><label className="products-search"><Search/><input value={search} onChange={event=>setSearch(event.target.value)} placeholder="Buscar por nombre o descripción..."/></label><OptionPicker label="Estado" value={status} options={[{value:"all",label:"Todos"},{value:"active",label:"Activos"},{value:"inactive",label:"Inactivos"}]} onChange={value=>{setCursor(undefined);setStatus(value)}}/></div>
    <div className="products-table-card"><div className="products-table__meta"><span>{page?.total??0} departamentos</span><OptionPicker label="Orden" value={sort} options={[{value:"name",label:"Nombre"},{value:"products",label:"Productos"},{value:"updatedAt",label:"Actualización"}]} onChange={value=>{setCursor(undefined);setSort(value)}}/><Button appearance="unstyled" aria-label="Cambiar dirección" onClick={()=>{setCursor(undefined);setDirection(value=>value==="asc"?"desc":"asc")}}>{direction==="asc"?<ArrowUp/>:<ArrowDown/>}</Button></div>
      <div className="category-table" role="table"><div className="category-table__head" role="row"><span>Departamento</span><span>Productos</span><span>Estado</span><span>Actualización</span><span/></div>{page?.items.map(category=><button key={category.id} className="category-table__row" type="button" role="row" onClick={()=>setSelectedId(category.id)}><span><strong>{category.name}</strong><small>{category.description??"Sin descripción"}</small></span><span>{category.productCount}</span><span><StatusBadge intent={category.status==="active"?"success":"neutral"}>{category.status==="active"?"Activo":"Inactivo"}</StatusBadge></span><span>{formatDate(category.updatedAt)}</span><ChevronRight/></button>)}</div>
      {!page?.items.length?<div className="products-empty"><Folders/><strong>No hay departamentos para estos filtros</strong><span>Prueba otra búsqueda o crea una categoría de productos.</span></div>:null}
      {page?.nextCursor?<footer className="products-pagination"><Button appearance="text" intent="neutral" onClick={()=>setCursor(page.nextCursor??undefined)}>Cargar más</Button></footer>:null}
    </div>
    {creating?<CategoryEditor organizationId={organizationId} companyId={companyId} onClose={()=>setCreating(false)} onSaved={async()=>{setCreating(false);refresh()}}/>:null}
    {selectedId?<CategoryDetail organizationId={organizationId} companyId={companyId} categoryId={selectedId} canUpdate={permissions.includes("inventory.update")} onClose={()=>setSelectedId(undefined)} onChanged={refresh}/>:null}
  </section>;
}

function CategorySummary({summary,total}:{readonly summary:NativeProductCategoryOverviewDto["summary"];readonly total:number}){return <div className="products-summary"><article><span>Total</span><strong>{total}</strong></article><article><span>Activos</span><strong>{summary.active}</strong></article><article><span>En uso</span><strong>{summary.inUse}</strong></article><article><span>Productos sin asignar</span><strong>{summary.unassignedProducts}</strong></article></div>}

function CategoryDetail({canUpdate,categoryId,companyId,onChanged,onClose,organizationId}:{readonly canUpdate:boolean;readonly categoryId:string;readonly companyId:string;readonly onChanged:()=>void;readonly onClose:()=>void;readonly organizationId:string}){
  const [category,setCategory]=useState<NativeProductCategoryOverviewItemDto>();const [products,setProducts]=useState<readonly NativeProductDto[]>([]);const [editing,setEditing]=useState(false);
  async function load(){const [detail,assigned]=await Promise.all([window.kontave.products.getCategory(organizationId,companyId,categoryId),window.kontave.products.list(organizationId,companyId,{categoryId,status:"all",stock:"all",sort:"name",direction:"asc",limit:25})]);if(detail.ok)setCategory(detail.value);else presentCategoryFailure(detail.error,onClose);if(assigned.ok)setProducts(assigned.value.items);else presentCategoryFailure(assigned.error)}
  useEffect(()=>{let active=true;void Promise.all([window.kontave.products.getCategory(organizationId,companyId,categoryId),window.kontave.products.list(organizationId,companyId,{categoryId,status:"all",stock:"all",sort:"name",direction:"asc",limit:25})]).then(([detail,assigned])=>{if(!active)return;if(detail.ok)setCategory(detail.value);else presentCategoryFailure(detail.error,onClose);if(assigned.ok)setProducts(assigned.value.items);else presentCategoryFailure(assigned.error)});return()=>{active=false}},[categoryId,companyId,onClose,organizationId]);
  if(!category)return <Dialog title="Departamento" onClose={onClose}><div className="category-detail-skeleton"><Skeleton variant="rectangle" width="100%" height={90}/><Skeleton variant="rectangle" width="100%" height={240}/></div></Dialog>;
  async function changeStatus(){const currentCategory=category;if(!currentCategory)return;const result=await runExclusiveMutation(currentCategory.status==="active"?"Desactivando departamento":"Reactivando departamento",()=>window.kontave.products.setCategoryStatus(organizationId,companyId,currentCategory.id,currentCategory.status!=="active",currentCategory.version));if(result.ok){await load();onChanged();presentFeedback.execute(successFeedback(currentCategory.status==="active"?"Departamento desactivado.":"Departamento reactivado."))}else presentCategoryFailure(result.error,load)}
  return <Dialog title={category.name} onClose={onClose} wide><div className="category-detail"><header><div><StatusBadge intent={category.status==="active"?"success":"neutral"}>{category.status==="active"?"Activo":"Inactivo"}</StatusBadge><span>{category.productCount} productos</span></div>{canUpdate?<div><Button appearance="text" intent="neutral" onClick={()=>setEditing(true)}>Editar</Button><Button appearance="text" intent="neutral" onClick={()=>void changeStatus()}><Archive/>{category.status==="active"?"Desactivar":"Reactivar"}</Button></div>:null}</header><p>{category.description??"Sin descripción."}</p><section><h3>Productos asignados</h3>{products.length?<div className="category-products">{products.map(product=><article key={product.id}><div><strong>{product.name}</strong><small>{product.sku||"Sin SKU"}</small></div><StatusBadge intent={product.status==="active"?"success":"neutral"}>{product.status==="active"?"Activo":"Inactivo"}</StatusBadge></article>)}</div>:<p>No hay productos asignados.</p>}{category.productCount>products.length?<small>Se muestran los primeros {products.length} productos.</small>:null}</section></div>{editing?<CategoryEditor organizationId={organizationId} companyId={companyId} category={category} onClose={()=>setEditing(false)} onSaved={async()=>{setEditing(false);await load();onChanged()}}/>:null}</Dialog>;
}

function CategoryEditor({category,companyId,onClose,onSaved,organizationId}:{readonly category?:NativeProductCategoryOverviewItemDto;readonly companyId:string;readonly onClose:()=>void;readonly onSaved:()=>Promise<void>;readonly organizationId:string}){const [name,setName]=useState(category?.name??"");const [description,setDescription]=useState(category?.description??"");const [version,setVersion]=useState(category?.version??1);async function refreshVersion(){if(!category)return;const latest=await window.kontave.products.getCategory(organizationId,companyId,category.id);if(latest.ok)setVersion(latest.value.version)}async function submit(event:FormEvent){event.preventDefault();const result=await runExclusiveMutation(category?"Guardando departamento":"Creando departamento",()=>category?window.kontave.products.updateCategory(organizationId,companyId,category.id,{name:name.trim(),description:description.trim()||null,expectedVersion:version}):window.kontave.products.createCategory(organizationId,companyId,{name:name.trim(),description:description.trim()||null}));if(result.ok){presentFeedback.execute(successFeedback(category?"Departamento actualizado.":"Departamento creado."));await onSaved()}else presentCategoryFailure(result.error,refreshVersion)}return <Dialog title={category?"Editar departamento":"Nuevo departamento"} onClose={onClose}><form className="product-form" onSubmit={event=>void submit(event)}><label className="product-field"><span>Nombre</span><input required maxLength={120} value={name} onChange={event=>setName(event.target.value)}/></label><label className="product-field"><span>Descripción</span><textarea rows={4} maxLength={500} value={description} onChange={event=>setDescription(event.target.value)}/></label><footer><Button type="button" appearance="text" intent="neutral" onClick={onClose}>Cancelar</Button><Button type="submit">{category?"Guardar cambios":"Crear departamento"}</Button></footer></form></Dialog>}

function Dialog({children,onClose,title,wide=false}:{readonly children:React.ReactNode;readonly onClose:()=>void;readonly title:string;readonly wide?:boolean}){return <div className="product-overlay" role="presentation" onMouseDown={event=>{if(event.target===event.currentTarget)onClose()}}><section className="product-dialog" data-wide={wide} role="dialog" aria-modal="true" aria-label={title}><header><h2>{title}</h2><Button appearance="unstyled" aria-label="Cerrar" onClick={onClose}><X/></Button></header>{children}</section></div>}
function CategorySkeleton(){return <section className="products-page" aria-busy="true"><div className="products-page__heading"><div><Skeleton variant="text" width={210} height={30}/><Skeleton variant="text" width={360}/></div></div><div className="products-summary">{Array.from({length:4},(_,index)=><Skeleton key={index} variant="rectangle" width="100%" height={82}/>)}</div><Skeleton variant="rectangle" width="100%" height={420}/></section>}
function presentCategoryFailure(error:{readonly code:string;readonly message:string;readonly requestId:string|null},onConflict?:()=>void|Promise<void>){if(error.code.includes("VERSION_CONFLICT")){presentFeedback.execute(codedErrorFeedback({code:error.requestId??error.code,message:"Este departamento cambió en otro cliente. Actualizamos la información para que puedas revisar tus cambios.",deduplicationKey:`category-conflict-${error.requestId??error.code}`}));void onConflict?.();return}presentFeedback.execute(codedErrorFeedback({code:error.requestId??error.code,message:error.message,deduplicationKey:`categories-${error.requestId??error.code}`}))}
function formatDate(value:string|null):string{if(!value)return "—";return new Intl.DateTimeFormat("es-VE",{day:"2-digit",month:"short",year:"numeric"}).format(new Date(value))}
