import { useEffect, useMemo, useRef, useState, type FormEvent } from "react";
import { Archive, ArrowDown, ArrowUp, Boxes, ChevronRight, PackagePlus, Plus, RefreshCw, Search, Tags, X } from "lucide-react";
import type { NativeProductCategoryDto, NativeProductDetailDto, NativeProductDto, NativeProductListDto, NativeProductMovementDto, NativeUnitOfMeasure } from "@kontave/native-api-contracts";
import { codedErrorFeedback, successFeedback } from "@kontave/client-feedback-application";
import { Button, OptionPicker, Skeleton, StatusBadge, presentFeedback } from "@kontave/ui-dom";
import type { DesktopProductListQuery } from "../../shared/desktop-api.js";
import { runExclusiveMutation } from "./client-interaction.js";

interface ProductsViewProps { readonly organizationId:string;readonly companyId:string }
type ProductStatusFilter = "active"|"inactive"|"all";
type StockFilter = "all"|"available"|"low"|"out";
type ProductSort = "name"|"sku"|"stock"|"value"|"updatedAt";

export function ProductsView({ companyId, organizationId }: ProductsViewProps) {
  const [page,setPage]=useState<NativeProductListDto>();
  const [categories,setCategories]=useState<readonly NativeProductCategoryDto[]>([]);
  const [loading,setLoading]=useState(true);
  const [refreshing,setRefreshing]=useState(false);
  const [search,setSearch]=useState("");
  const [debouncedSearch,setDebouncedSearch]=useState("");
  const [status,setStatus]=useState<ProductStatusFilter>("active");
  const [stock,setStock]=useState<StockFilter>("all");
  const [categoryId,setCategoryId]=useState("all");
  const [sort,setSort]=useState<ProductSort>("name");
  const [direction,setDirection]=useState<"asc"|"desc">("asc");
  const [cursor,setCursor]=useState<string>();
  const [selectedId,setSelectedId]=useState<string>();
  const [creating,setCreating]=useState(false);
  const [categoryManager,setCategoryManager]=useState(false);
  const [permissions,setPermissions]=useState<readonly string[]>([]);
  const requestSequence=useRef(0);

  useEffect(()=>{const timer=window.setTimeout(()=>{setCursor(undefined);setDebouncedSearch(search.trim())},300);return()=>window.clearTimeout(timer);},[search]);
  const query=useMemo<DesktopProductListQuery>(()=>({search:debouncedSearch,status,stock,sort,direction,limit:25,...(categoryId!=="all"?{categoryId}:{}),...(cursor?{cursor}:{})}),[categoryId,cursor,debouncedSearch,direction,sort,status,stock]);

  async function load(showSkeleton=false):Promise<void>{
    if(showSkeleton)setLoading(true);else setRefreshing(true);
    const result=await window.kontave.products.list(organizationId,companyId,query);
    if(result.ok)setPage(result.value);else presentProductFailure(result.error);
    setLoading(false);setRefreshing(false);
  }
  async function loadCategories(filter:"active"|"all"="active"):Promise<void>{const result=await window.kontave.products.categories(organizationId,companyId,filter);if(result.ok)setCategories(result.value);else presentProductFailure(result.error);}
  useEffect(()=>{let active=true;const sequence=++requestSequence.current;void Promise.all([window.kontave.products.list(organizationId,companyId,query),window.kontave.products.categories(organizationId,companyId,"active"),window.kontave.products.permissions(organizationId)]).then(([productsResult,categoriesResult,permissionsResult])=>{if(!active||sequence!==requestSequence.current)return;if(productsResult.ok)setPage(current=>cursor&&current?{...productsResult.value,items:[...current.items,...productsResult.value.items]}:productsResult.value);else presentProductFailure(productsResult.error);if(categoriesResult.ok)setCategories(categoriesResult.value);else presentProductFailure(categoriesResult.error);if(permissionsResult.ok)setPermissions(permissionsResult.value);else presentProductFailure(permissionsResult.error);setLoading(false);});return()=>{active=false};},[companyId,cursor,organizationId,query]);

  if(loading&&!page)return <ProductsSkeleton/>;
  return <section className="products-page">
    <header className="products-page__heading"><div><h2>Productos</h2><p>Catálogo, existencia y valoración de la empresa seleccionada.</p></div><div><Button appearance="unstyled" aria-label="Actualizar productos" onClick={()=>void load()}><RefreshCw className={refreshing?"is-spinning":undefined}/></Button><Button appearance="text" intent="neutral" onClick={()=>{setCategoryManager(true);void loadCategories("all")}}><Tags/>Categorías</Button>{permissions.includes("inventory.create")?<Button onClick={()=>setCreating(true)}><Plus/>Nuevo producto</Button>:null}</div></header>
    {page?<ProductSummary summary={page.summary}/>:null}
    <div className="products-toolbar">
      <label className="products-search"><Search/><input value={search} onChange={event=>setSearch(event.target.value)} placeholder="Buscar por nombre, SKU o código de barras..."/></label>
      <OptionPicker label="Estado" value={status} options={[{value:"active",label:"Activos"},{value:"inactive",label:"Inactivos"},{value:"all",label:"Todos"}]} onChange={value=>{setCursor(undefined);setStatus(value)}}/>
      <OptionPicker label="Existencia" value={stock} options={[{value:"all",label:"Cualquier stock"},{value:"available",label:"Disponible"},{value:"low",label:"Stock bajo"},{value:"out",label:"Agotado"}]} onChange={value=>{setCursor(undefined);setStock(value)}}/>
      <OptionPicker label="Categoría" value={categoryId} searchable searchPlaceholder="Buscar categoría..." options={[{value:"all",label:"Todas"},...categories.map(category=>({value:category.id,label:category.name}))]} onChange={value=>{setCursor(undefined);setCategoryId(value)}}/>
    </div>
    <div className="products-table-card">
      <div className="products-table__meta"><span>{page?.total??0} productos</span><OptionPicker label="Orden" value={sort} options={[{value:"name",label:"Nombre"},{value:"sku",label:"SKU"},{value:"stock",label:"Existencia"},{value:"value",label:"Valor"},{value:"updatedAt",label:"Actualización"}]} onChange={value=>{setCursor(undefined);setSort(value)}}/><Button appearance="unstyled" aria-label="Cambiar dirección" onClick={()=>{setCursor(undefined);setDirection(value=>value==="asc"?"desc":"asc")}}>{direction==="asc"?<ArrowUp/>:<ArrowDown/>}</Button></div>
      <div className="products-table" role="table"><div className="products-table__head" role="row"><span>Producto</span><span>Categoría</span><span>Existencia</span><span>Costo unitario</span><span>Valor</span><span>Estado</span><span/></div>{page?.items.map(product=><ProductRow key={product.id} product={product} onOpen={()=>setSelectedId(product.id)}/>)}</div>
      {!page?.items.length?<div className="products-empty"><Boxes/><strong>No hay productos para estos filtros</strong><span>Prueba otra búsqueda o registra un nuevo producto.</span></div>:null}
      {page?.nextCursor?<footer className="products-pagination"><Button appearance="text" intent="neutral" onClick={()=>setCursor(page.nextCursor??undefined)}>Cargar más</Button></footer>:null}
    </div>
    {creating?<ProductEditor organizationId={organizationId} companyId={companyId} categories={categories} onClose={()=>setCreating(false)} onSaved={async()=>{setCreating(false);setCursor(undefined);await load()}}/>:null}
    {selectedId?<ProductDetail organizationId={organizationId} companyId={companyId} productId={selectedId} categories={categories} canUpdate={permissions.includes("inventory.update")} onClose={()=>setSelectedId(undefined)} onChanged={load}/>:null}
    {categoryManager?<CategoryManager organizationId={organizationId} companyId={companyId} categories={categories} canCreate={permissions.includes("inventory.create")} canUpdate={permissions.includes("inventory.update")} onClose={()=>{setCategoryManager(false);void loadCategories()}} onRefresh={()=>loadCategories("all")}/>:null}
  </section>;
}

function ProductSummary({summary}:{readonly summary:NativeProductListDto["summary"]}){return <div className="products-summary"><article><span>Activos</span><strong>{summary.active}</strong></article><article><span>Stock bajo</span><strong>{summary.lowStock}</strong></article><article><span>Agotados</span><strong>{summary.outOfStock}</strong></article><article><span>Valor del inventario</span><strong>{formatMoney(summary.inventoryValue.amount)}</strong></article></div>}
function ProductRow({onOpen,product}:{readonly onOpen:()=>void;readonly product:NativeProductDto}){return <button className="products-table__row" type="button" role="row" onClick={onOpen}><span><strong>{product.name}</strong><small>{product.sku}</small></span><span>{product.category?.name??"Sin categoría"}</span><span>{product.inventory?`${formatDecimal(product.inventory.onHand.quantity)} ${unitLabel(product.inventory.onHand.unit)}`:"—"}</span><span>{product.inventory?formatMoney(product.inventory.valuation.unitCost):"—"}</span><span>{product.inventory?formatMoney(product.inventory.valuation.totalValue):"—"}</span><span><StatusBadge intent={product.status==="inactive"?"neutral":stockIntent(product.inventory?.replenishment.state)}>{product.status==="inactive"?"Inactivo":stockLabel(product.inventory?.replenishment.state)}</StatusBadge></span><ChevronRight/></button>}

function ProductEditor({categories,companyId,onClose,onConflict,onSaved,organizationId,product}:{readonly categories:readonly NativeProductCategoryDto[];readonly companyId:string;readonly onClose:()=>void;readonly onConflict?:()=>void|Promise<void>;readonly onSaved:()=>Promise<void>;readonly organizationId:string;readonly product?:NativeProductDetailDto}){
  const [sku,setSku]=useState(product?.sku??"");const [name,setName]=useState(product?.name??"");const [description,setDescription]=useState(product?.description??"");const [barcodes,setBarcodes]=useState(product?.barcodes.join(", ")??"");const [category,setCategory]=useState(product?.category?.id??"");const [unit,setUnit]=useState<NativeUnitOfMeasure>(product?.baseUnit??"each");const [version,setVersion]=useState(product?.version??1);
  async function refreshVersion(){if(product){const latest=await window.kontave.products.get(organizationId,companyId,product.id);if(latest.ok)setVersion(latest.value.version)}await onConflict?.()}
  async function submit(event:FormEvent){event.preventDefault();const codes=barcodes.split(",").map(value=>value.trim()).filter(Boolean);const result=await runExclusiveMutation(product?"Guardando producto":"Creando producto",()=>product?window.kontave.products.update(organizationId,companyId,product.id,{sku:sku.trim(),name:name.trim(),description:description.trim()||null,barcodes:codes,categoryId:category||null,baseUnit:unit,expectedVersion:version}):window.kontave.products.create(organizationId,companyId,{sku:sku.trim(),name:name.trim(),description:description.trim()||null,barcodes:codes,categoryId:category||null,baseUnit:unit}));if(result.ok){presentFeedback.execute(successFeedback(product?"Producto actualizado.":"Producto creado."));await onSaved()}else presentProductFailure(result.error,refreshVersion)}
  return <Overlay title={product?"Editar producto":"Nuevo producto"} onClose={onClose}><form className="product-form" onSubmit={event=>void submit(event)}><Field label="Nombre"><input required value={name} onChange={event=>setName(event.target.value)}/></Field><div className="product-form__columns"><Field label="SKU"><input required value={sku} onChange={event=>setSku(event.target.value)}/></Field><Field label="Unidad base"><select value={unit} onChange={event=>setUnit(event.target.value as NativeUnitOfMeasure)}>{UNITS.map(value=><option key={value} value={value}>{unitLabel(value)}</option>)}</select></Field></div><Field label="Categoría"><select value={category} onChange={event=>setCategory(event.target.value)}><option value="">Sin categoría</option>{categories.filter(value=>value.status==="active").map(value=><option key={value.id} value={value.id}>{value.name}</option>)}</select></Field><Field label="Códigos de barras" hint="Sepáralos con comas."><input value={barcodes} onChange={event=>setBarcodes(event.target.value)}/></Field><Field label="Descripción"><textarea rows={3} value={description} onChange={event=>setDescription(event.target.value)}/></Field><footer><Button type="button" appearance="text" intent="neutral" onClick={onClose}>Cancelar</Button><Button type="submit">{product?"Guardar cambios":"Crear producto"}</Button></footer></form></Overlay>}

function ProductDetail({canUpdate,categories,companyId,onChanged,onClose,organizationId,productId}:{readonly canUpdate:boolean;readonly categories:readonly NativeProductCategoryDto[];readonly companyId:string;readonly onChanged:()=>Promise<void>;readonly onClose:()=>void;readonly organizationId:string;readonly productId:string}){
  const [product,setProduct]=useState<NativeProductDetailDto>();const [movements,setMovements]=useState<readonly NativeProductMovementDto[]>([]);const [nextCursor,setNextCursor]=useState<string|null>(null);const [editing,setEditing]=useState(false);const [minimum,setMinimum]=useState("");
  async function load(){const [detail,movementPage]=await Promise.all([window.kontave.products.get(organizationId,companyId,productId),window.kontave.products.movements(organizationId,companyId,productId,{limit:25})]);if(detail.ok){setProduct(detail.value);setMinimum(detail.value.inventory?.replenishment.minimumQuantity??"")}else presentProductFailure(detail.error,onClose);if(movementPage.ok){setMovements(movementPage.value.items);setNextCursor(movementPage.value.nextCursor)}else presentProductFailure(movementPage.error)}
  useEffect(()=>{let active=true;void Promise.all([window.kontave.products.get(organizationId,companyId,productId),window.kontave.products.movements(organizationId,companyId,productId,{limit:25})]).then(([detail,movementPage])=>{if(!active)return;if(detail.ok){setProduct(detail.value);setMinimum(detail.value.inventory?.replenishment.minimumQuantity??"")}else presentProductFailure(detail.error);if(movementPage.ok){setMovements(movementPage.value.items);setNextCursor(movementPage.value.nextCursor)}else presentProductFailure(movementPage.error)});return()=>{active=false}},[companyId,organizationId,productId]);
  if(!product)return <Overlay title="Producto" onClose={onClose}><DetailSkeleton/></Overlay>;
  const currentProduct=product;
  async function statusChange(){const result=await runExclusiveMutation(currentProduct.status==="active"?"Desactivando producto":"Reactivando producto",()=>window.kontave.products.setStatus(organizationId,companyId,currentProduct.id,currentProduct.status!=="active",currentProduct.version));if(result.ok){await load();await onChanged();presentFeedback.execute(successFeedback(currentProduct.status==="active"?"Producto desactivado.":"Producto reactivado."))}else presentProductFailure(result.error,load)}
  async function saveMinimum(event:FormEvent){event.preventDefault();if(!currentProduct.inventory)return;const result=await runExclusiveMutation("Guardando stock mínimo",()=>window.kontave.products.updateInventoryProfile(organizationId,companyId,currentProduct.id,{minimumQuantity:minimum.trim()||null,expectedVersion:currentProduct.inventory!.replenishment.version}));if(result.ok){await load();await onChanged();presentFeedback.execute(successFeedback("Stock mínimo actualizado."))}else presentProductFailure(result.error,load)}
  if(!canUpdate)return <Overlay title={product.name} onClose={onClose} wide><div className="product-detail"><header><div><span>{product.sku}</span><StatusBadge intent={product.status==="active"?"success":"neutral"}>{product.status==="active"?"Activo":"Inactivo"}</StatusBadge></div></header><dl><div><dt>Categoría</dt><dd>{product.category?.name??"Sin categoría"}</dd></div><div><dt>Unidad</dt><dd>{unitLabel(product.baseUnit)}</dd></div><div><dt>Existencia</dt><dd>{product.inventory?formatDecimal(product.inventory.onHand.quantity):"—"}</dd></div><div><dt>Valoración</dt><dd>{product.inventory?formatMoney(product.inventory.valuation.totalValue):"—"}</dd></div></dl><MovementList movements={movements}/></div></Overlay>;
  return <Overlay title={product.name} onClose={onClose} wide><div className="product-detail"><header><div><span>{product.sku}</span><StatusBadge intent={product.status==="active"?"success":"neutral"}>{product.status==="active"?"Activo":"Inactivo"}</StatusBadge></div><div><Button appearance="text" intent="neutral" onClick={()=>setEditing(true)}>Editar</Button><Button appearance="text" intent="neutral" onClick={()=>void statusChange()}>{product.status==="active"?<Archive/>:<PackagePlus/>}{product.status==="active"?"Desactivar":"Reactivar"}</Button></div></header><dl><div><dt>Categoría</dt><dd>{product.category?.name??"Sin categoría"}</dd></div><div><dt>Unidad</dt><dd>{unitLabel(product.baseUnit)}</dd></div><div><dt>Existencia</dt><dd>{product.inventory?formatDecimal(product.inventory.onHand.quantity):"—"}</dd></div><div><dt>Valoración</dt><dd>{product.inventory?formatMoney(product.inventory.valuation.totalValue):"—"}</dd></div></dl>{product.capabilities.inventoryEnabled&&product.inventory?<form className="product-minimum" onSubmit={event=>void saveMinimum(event)}><div><strong>Stock mínimo</strong><small>El servidor determina el estado de reposición.</small></div><input inputMode="decimal" value={minimum} onChange={event=>setMinimum(event.target.value)} placeholder="Sin mínimo"/><Button type="submit" appearance="text" intent="neutral">Guardar</Button></form>:null}<section className="product-movements"><h3>Movimientos recientes</h3>{movements.length?<div>{movements.map(movement=><article key={movement.id}><div><strong>{movement.type}</strong><small>{formatDate(movement.effectiveDate)} · {movement.reference??"Sin referencia"}</small></div><div><strong>{formatSigned(movement.quantity.value)} {unitLabel(movement.quantity.unit)}</strong><small>Saldo {formatDecimal(movement.balanceQuantity)} · {formatMoney(movement.totalCost.amount)}</small></div></article>)}</div>:<p>No hay movimientos registrados.</p>}{nextCursor?<Button appearance="text" intent="neutral" onClick={async()=>{const result=await window.kontave.products.movements(organizationId,companyId,product.id,{cursor:nextCursor,limit:25});if(result.ok){setMovements(current=>[...current,...result.value.items]);setNextCursor(result.value.nextCursor)}else presentProductFailure(result.error)}}>Cargar más</Button>:null}</section></div>{editing?<ProductEditor product={product} categories={categories} organizationId={organizationId} companyId={companyId} onClose={()=>setEditing(false)} onSaved={async()=>{setEditing(false);await load();await onChanged()}}/>:null}</Overlay>}

function CategoryManager({canCreate,canUpdate,categories,companyId,onClose,onRefresh,organizationId}:{readonly canCreate:boolean;readonly canUpdate:boolean;readonly categories:readonly NativeProductCategoryDto[];readonly companyId:string;readonly onClose:()=>void;readonly onRefresh:()=>Promise<void>;readonly organizationId:string}){
  const [name,setName]=useState("");const [description,setDescription]=useState("");const [editing,setEditing]=useState<NativeProductCategoryDto>();
  function reset(){setName("");setDescription("");setEditing(undefined)}
  async function save(event:FormEvent){event.preventDefault();const result=await runExclusiveMutation(editing?"Guardando categoría":"Creando categoría",()=>editing?window.kontave.products.updateCategory(organizationId,companyId,editing.id,{name:name.trim(),description:description.trim()||null,expectedVersion:editing.version}):window.kontave.products.createCategory(organizationId,companyId,{name:name.trim(),description:description.trim()||null}));if(result.ok){reset();await onRefresh();presentFeedback.execute(successFeedback(editing?"Categoría actualizada.":"Categoría creada."))}else presentProductFailure(result.error,onRefresh)}
  return <Overlay title="Categorías" onClose={onClose}><div className="category-manager">{canCreate||editing?<form onSubmit={event=>void save(event)}><input required value={name} onChange={event=>setName(event.target.value)} placeholder="Nombre de la categoría"/><input value={description} onChange={event=>setDescription(event.target.value)} placeholder="Descripción opcional"/>{editing?<Button type="button" appearance="unstyled" onClick={reset}>Cancelar</Button>:null}<Button type="submit"><Plus/>{editing?"Guardar":"Agregar"}</Button></form>:null}<div>{categories.map(category=><article key={category.id}><div><strong>{category.name}</strong><small>{category.status==="active"?"Activa":"Inactiva"}{category.description?` · ${category.description}`:""}</small></div>{canUpdate?<span><Button size="sm" appearance="unstyled" onClick={()=>{setEditing(category);setName(category.name);setDescription(category.description??"")}}>Editar</Button><Button size="sm" appearance="unstyled" onClick={async()=>{const result=await runExclusiveMutation("Actualizando categoría",()=>window.kontave.products.setCategoryStatus(organizationId,companyId,category.id,category.status!=="active",category.version));if(result.ok)await onRefresh();else presentProductFailure(result.error,onRefresh)}}>{category.status==="active"?"Desactivar":"Reactivar"}</Button></span>:null}</article>)}</div></div></Overlay>}

function MovementList({movements}:{readonly movements:readonly NativeProductMovementDto[]}){return <section className="product-movements"><h3>Movimientos recientes</h3>{movements.length?<div>{movements.map(movement=><article key={movement.id}><div><strong>{movement.type}</strong><small>{formatDate(movement.effectiveDate)} · {movement.reference??"Sin referencia"}</small></div><div><strong>{formatSigned(movement.quantity.value)} {unitLabel(movement.quantity.unit)}</strong><small>Saldo {formatDecimal(movement.balanceQuantity)} · {formatMoney(movement.totalCost.amount)}</small></div></article>)}</div>:<p>No hay movimientos registrados.</p>}</section>}

function Overlay({children,onClose,title,wide=false}:{readonly children:React.ReactNode;readonly onClose:()=>void;readonly title:string;readonly wide?:boolean}){return <div className="product-overlay" role="presentation" onMouseDown={event=>{if(event.target===event.currentTarget)onClose()}}><section className="product-dialog" data-wide={wide} role="dialog" aria-modal="true" aria-label={title}><header><h2>{title}</h2><Button appearance="unstyled" aria-label="Cerrar" onClick={onClose}><X/></Button></header>{children}</section></div>}
function Field({children,hint,label}:{readonly children:React.ReactNode;readonly hint?:string;readonly label:string}){return <label className="product-field"><span>{label}</span>{children}{hint?<small>{hint}</small>:null}</label>}
function ProductsSkeleton(){return <section className="products-page" aria-busy="true"><div className="products-page__heading"><div><Skeleton variant="text" width={180} height={30}/><Skeleton variant="text" width={340}/></div></div><div className="products-summary">{Array.from({length:4},(_,index)=><Skeleton key={index} variant="rectangle" width="100%" height={82}/>)}</div><Skeleton variant="rectangle" width="100%" height={420}/></section>}
function DetailSkeleton(){return <div className="product-detail-skeleton" aria-busy="true"><Skeleton variant="rectangle" width="100%" height={100}/><Skeleton variant="rectangle" width="100%" height={220}/></div>}
function presentProductFailure(error:{readonly code:string;readonly message:string;readonly requestId:string|null},onConflict?:()=>void|Promise<void>){if(error.code.includes("VERSION_CONFLICT")){presentFeedback.execute(codedErrorFeedback({code:error.requestId??error.code,message:"Este registro cambió en otro cliente. Actualizamos la información para que puedas revisar y reaplicar tus cambios.",deduplicationKey:`product-conflict-${error.requestId??error.code}`}));void onConflict?.();return}presentFeedback.execute(codedErrorFeedback({code:error.requestId??error.code,message:error.message,deduplicationKey:`products-${error.requestId??error.code}`}))}
const UNITS:readonly NativeUnitOfMeasure[]=["each","kilogram","gram","meter","square_meter","cubic_meter","liter","gallon","box","roll","package"];
function unitLabel(unit:NativeUnitOfMeasure):string{return({each:"unid.",kilogram:"kg",gram:"g",meter:"m",square_meter:"m²",cubic_meter:"m³",liter:"L",gallon:"gal",box:"caja",roll:"rollo",package:"paquete"})[unit]}
function stockLabel(state:NativeProductDto["inventory"] extends infer _T?"available"|"low"|"out"|undefined:never):string{return state==="low"?"Stock bajo":state==="out"?"Agotado":"Disponible"}
function stockIntent(state:"available"|"low"|"out"|undefined):"success"|"warning"|"danger"{return state==="low"?"warning":state==="out"?"danger":"success"}
function formatDecimal(value:string):string{const [integer,fraction]=value.split(".");const sign=integer?.startsWith("-")?"-":"";const digits=(integer??"0").replace("-","").replace(/^0+(?=\d)/,"");const grouped=digits.replace(/\B(?=(\d{3})+(?!\d))/g,".");const decimals=(fraction??"").replace(/0+$/,"");return `${sign}${grouped}${decimals?`,${decimals}`:""}`}
function formatMoney(value:string):string{return `${formatDecimal(roundDisplay(value))} VES`}
function roundDisplay(value:string):string{const [integer="0",fraction=""]=value.split(".");return `${integer}.${fraction.padEnd(2,"0").slice(0,2)}`}
function formatSigned(value:string):string{return value.startsWith("-")?formatDecimal(value):`+${formatDecimal(value)}`}
function formatDate(value:string):string{return new Intl.DateTimeFormat("es-VE",{day:"2-digit",month:"short",year:"numeric",timeZone:"UTC"}).format(new Date(`${value}T00:00:00Z`))}
