export { DESKTOP_IPC } from "./protocol/channels";
export type * from "./core/result";
export type * from "./core/client-runtime";
export type * from "./domains/authentication";
export type * from "./domains/billing";
export type * from "./domains/connectivity";
export type * from "./domains/devices";
export type * from "./domains/inventory";
export type * from "./domains/navigation";
export type * from "./domains/platform-status";
export type * from "./domains/products";
export type * from "./domains/profile";
export type * from "./domains/purchasing";
export type * from "./domains/sales";
export type * from "./domains/settings";
export type * from "./domains/updates";
export type * from "./domains/workspace";
export type * from "./renderer-bridge";
