// Application layer — reverses the accounting entries previously generated by
// `ProcessPayrollIntegrationUseCase` when a payroll run is unconfirmed.
// Non-blocking by design: errors are logged and Result.success is returned so
// the payroll unconfirm operation is never rolled back by an accounting failure.
import { Result }                     from '@/src/core/domain/result';
import { IIntegrationLogRepository }  from '../../domain/repository/integration-log.repository';
import { IJournalEntryRepository }    from '../../domain/repository/journal-entry.repository';

export interface ReversePayrollInput {
    companyId:    string;
    payrollRunId: string;
}

export class ReversePayrollIntegrationUseCase {
    constructor(
        private readonly logRepo:   IIntegrationLogRepository,
        private readonly entryRepo: IJournalEntryRepository,
    ) {}

    async execute(input: ReversePayrollInput): Promise<Result<void>> {
        const result = await this.entryRepo.deleteBySourceRef(
            input.companyId,
            'payroll',
            input.payrollRunId,
        );

        if (result.isFailure) {
            await this.log(input, null, 'error', result.getError());
            return Result.success(undefined);
        }

        const deletedIds = result.getValue();
        if (deletedIds.length === 0) {
            await this.log(input, null, 'skipped', 'No había asientos contables que revertir');
            return Result.success(undefined);
        }

        for (const entryId of deletedIds) {
            await this.log(input, entryId, 'success', null);
        }

        return Result.success(undefined);
    }

    private async log(
        input:   ReversePayrollInput,
        entryId: string | null,
        status:  string,
        error:   string | null,
    ) {
        await this.logRepo.save({
            companyId:    input.companyId,
            source:       'payroll_reversal',
            sourceRef:    input.payrollRunId,
            entryId,
            status,
            errorMessage: error,
        });
    }
}
