import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Providers } from "./provider";
import { redirect } from "next/navigation";
import { getAuthActions } from "@/src/backend/auth/infra/auth-factory";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // 1. Obtenemos el caso de uso 'me' desde nuestro factory
  const { me } = getAuthActions();
  
  // 2. Ejecutamos la verificación de sesión (Server Side)
  const result = await me.execute();

  // 3. Lógica de redirección
  // Si no hay usuario y no estamos ya en la ruta /un-auth, redirigimos
  if (result.isFailure || !result.getValue()) {
    // Nota: Debes tener cuidado de no crear un bucle infinito de redirecciones
    // redirect("/un-auth"); 
  }

  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  );
}