import { createClient, type SupabaseClient } from "@supabase/supabase-js";
import { companyId } from "@kontave/companies-domain";
import type {
  CreateProductCategoryCommand, CreateProductCommand, ProductCatalogContext, ProductCategoryListQuery,
  ProductCursorPage, ProductDetail, ProductListQuery, ProductMovementPage, ProductMovementQuery,
  ProductsRepository, ProductVersionCommand, UpdateProductCategoryCommand, UpdateProductCommand,
  ProductCategoryVersionCommand,
} from "@kontave/products-application";
import {
  barcode, Product, ProductCategory, ProductCategoryStatus, ProductFailure, productCategoryId, productId,
  ProductStatus, rehydrateSku, UnitOfMeasure,
} from "@kontave/products-domain";
import { z } from "zod";

const unit=z.nativeEnum(UnitOfMeasure);const status=z.nativeEnum(ProductStatus);const categoryStatus=z.nativeEnum(ProductCategoryStatus);
const categorySchema=z.object({id:z.string(),companyId:z.string(),legacyCategoryId:z.string().nullable(),name:z.string(),description:z.string().nullable(),status:categoryStatus,version:z.number().int().positive()});
const inventorySchema=z.object({onHand:z.object({quantity:z.string(),unit}),replenishment:z.object({minimumQuantity:z.string().nullable(),state:z.enum(["available","low","out"]),version:z.number().int().positive(),updatedAt:z.string()}),valuation:z.object({unitCost:z.string(),totalValue:z.string(),currency:z.literal("VES")})});
const productSchema=z.object({id:z.string(),companyId:z.string(),legacyProductId:z.string().nullable(),sku:z.string(),barcodes:z.array(z.string()),name:z.string(),description:z.string().nullable(),category:categorySchema.nullable(),baseUnit:unit,status,version:z.number().int().positive(),inventory:inventorySchema.nullable(),updatedAt:z.string(),capabilities:z.object({inventoryEnabled:z.boolean(),locationTracking:z.boolean(),lotTracking:z.boolean()})});
const pageSchema=z.object({items:z.array(productSchema),nextCursor:z.string().nullable(),total:z.number().int().nonnegative(),summary:z.object({active:z.number().int().nonnegative(),inactive:z.number().int().nonnegative(),lowStock:z.number().int().nonnegative(),outOfStock:z.number().int().nonnegative(),inventoryValue:z.object({amount:z.string(),currency:z.literal("VES")})})});
const movementPageSchema=z.object({items:z.array(z.object({id:z.string(),effectiveDate:z.string(),type:z.string(),quantity:z.object({value:z.string(),unit}),unitCost:z.object({amount:z.string(),currency:z.literal("VES")}),totalCost:z.object({amount:z.string(),currency:z.literal("VES")}),balanceQuantity:z.string(),reference:z.string().nullable(),notes:z.string().nullable(),createdAt:z.string()})),nextCursor:z.string().nullable()});

export class SupabaseProductsRepository implements ProductsRepository {
  constructor(private readonly client:SupabaseClient){}
  async list(query:ProductListQuery):Promise<ProductCursorPage>{const data=await this.rpc("list_native_products",{...context(query),p_search:query.search,p_status:query.status,p_category_id:query.categoryId,p_stock:query.stock,p_sort:query.sort,p_direction:query.direction,p_cursor:query.cursor,p_limit:query.limit});const parsed=parse(pageSchema,data);return{...parsed,items:parsed.items.map(mapDetail)};}
  async get(input:ProductCatalogContext,id:ReturnType<typeof productId>):Promise<ProductDetail|null>{const data=await this.rpc("get_native_product",{...context(input),p_product_id:id});if(data===null)return null;return mapDetail(parse(productSchema,data));}
  async create(command:CreateProductCommand):Promise<ProductDetail>{return mapDetail(parse(productSchema,await this.rpc("create_native_product",{...context(command),p_sku:command.sku,p_barcodes:command.barcodes,p_name:command.name,p_description:command.description,p_category_id:command.categoryId,p_base_unit:command.baseUnit})));}
  async update(command:UpdateProductCommand):Promise<ProductDetail>{const changes:Record<string,unknown>={};if(command.sku!==undefined)changes.sku=command.sku;if(command.barcodes!==undefined)changes.barcodes=command.barcodes;if(command.name!==undefined)changes.name=command.name;if(command.description!==undefined)changes.description=command.description;if(command.categoryId!==undefined)changes.categoryId=command.categoryId;if(command.baseUnit!==undefined)changes.baseUnit=command.baseUnit;return mapDetail(parse(productSchema,await this.rpc("update_native_product",{...context(command),p_product_id:command.productId,p_expected_version:command.expectedVersion,p_changes:changes})));}
  async setStatus(command:ProductVersionCommand,target:ProductStatus):Promise<ProductDetail>{return mapDetail(parse(productSchema,await this.rpc("set_native_product_status",{...context(command),p_product_id:command.productId,p_expected_version:command.expectedVersion,p_status:target})));}
  async listMovements(query:ProductMovementQuery):Promise<ProductMovementPage>{return parse(movementPageSchema,await this.rpc("list_native_product_movements",{...context(query),p_product_id:query.productId,p_from:query.from,p_to:query.to,p_type:query.type,p_location_id:query.locationId,p_cursor:query.cursor,p_limit:query.limit}));}
  async listCategories(query:ProductCategoryListQuery):Promise<readonly ProductCategory[]>{return parse(z.array(categorySchema),await this.rpc("list_native_product_categories",{...context(query),p_status:query.status})).map(mapCategory);}
  async createCategory(command:CreateProductCategoryCommand):Promise<ProductCategory>{return mapCategory(parse(categorySchema,await this.rpc("save_native_product_category",{...context(command),p_category_id:null,p_expected_version:null,p_name:command.name,p_description:command.description})));}
  async updateCategory(command:UpdateProductCategoryCommand):Promise<ProductCategory>{const current=(await this.listCategories({...command,status:"all"})).find(value=>value.id===command.categoryId);if(!current)throw new ProductFailure("PRODUCT_CATEGORY_NOT_FOUND","Product category was not found.");return mapCategory(parse(categorySchema,await this.rpc("save_native_product_category",{...context(command),p_category_id:command.categoryId,p_expected_version:command.expectedVersion,p_name:command.name??current.name,p_description:command.description===undefined?current.description:command.description})));}
  async setCategoryStatus(command:ProductCategoryVersionCommand,target:ProductCategoryStatus):Promise<ProductCategory>{return mapCategory(parse(categorySchema,await this.rpc("set_native_product_category_status",{...context(command),p_category_id:command.categoryId,p_expected_version:command.expectedVersion,p_status:target})));}
  private async rpc(name:string,args:Record<string,unknown>):Promise<unknown>{const{data,error}=await this.client.rpc(name,args);if(error)throw mapError(error);return data;}
}
export function createSupabaseProductsRepository(configuration:{readonly url:string;readonly serviceRoleKey:string}){return new SupabaseProductsRepository(createClient(configuration.url,configuration.serviceRoleKey,{auth:{persistSession:false,autoRefreshToken:false,detectSessionInUrl:false}}));}
function context(value:ProductCatalogContext){return{p_actor_user_id:value.actorUserId,p_organization_id:value.organizationId,p_company_id:value.companyId};}
function mapCategory(value:z.infer<typeof categorySchema>){return new ProductCategory({...value,id:productCategoryId(value.id),companyId:companyId(value.companyId)});}
function mapDetail(value:z.infer<typeof productSchema>):ProductDetail{return{product:new Product({id:productId(value.id),companyId:companyId(value.companyId),legacyProductId:value.legacyProductId,sku:rehydrateSku(value.sku,value.legacyProductId),barcodes:value.barcodes.map(barcode),name:value.name,description:value.description,categoryId:value.category?productCategoryId(value.category.id):null,baseUnit:value.baseUnit,status:value.status,version:value.version}),category:value.category?mapCategory(value.category):null,inventory:value.inventory,updatedAt:value.updatedAt,capabilities:value.capabilities};}
function parse<T extends z.ZodType>(schema:T,value:unknown):z.infer<T>{const result=schema.safeParse(value);if(!result.success)throw new ProductFailure("PRODUCT_REPOSITORY_UNAVAILABLE","Product persistence returned invalid data.",{cause:result.error});return result.data;}
function mapError(error:{message:string}):ProductFailure{const codes=["PRODUCT_CATEGORY_VERSION_CONFLICT","PRODUCT_LOCATION_TRACKING_UNAVAILABLE","PRODUCT_DUPLICATE_BARCODE","PRODUCT_DUPLICATE_CATEGORY","PRODUCT_DUPLICATE_SKU","PRODUCT_VERSION_CONFLICT","PRODUCT_CATEGORY_NOT_FOUND","PRODUCT_NOT_FOUND","PRODUCT_OUTSIDE_COMPANY","PRODUCT_ACCESS_DENIED","PRODUCT_TRANSITION_INVALID","PRODUCT_CATEGORY_INVALID","PRODUCT_INVALID"]as const;const code=codes.find(value=>error.message.includes(value));return new ProductFailure(code??"PRODUCT_REPOSITORY_UNAVAILABLE",code?error.message:"Product repository is unavailable.",{cause:error});}
