export type SalesFailureCode =
  | "SALES_ACCESS_DENIED"
  | "SALES_CREDIT_INVALID"
  | "SALES_IDENTIFIER_INVALID"
  | "SALES_DATE_INVALID"
  | "CUSTOMER_INVALID"
  | "CUSTOMER_INACTIVE"
  | "SALES_ORDER_INVALID"
  | "SALES_ORDER_TRANSITION_INVALID"
  | "SALES_DISPATCH_INVALID"
  | "SALES_DISPATCH_TRANSITION_INVALID"
  | "CUSTOMER_RETURN_INVALID"
  | "CUSTOMER_RETURN_TRANSITION_INVALID"
  | "CUSTOMER_INVOICE_MATCH_INVALID"
  | "SALES_CURRENCY_MISMATCH"
  | "SALES_QUANTITY_EXCEEDED"
  | "SALES_NOT_FOUND"
  | "SALES_CONCURRENCY_CONFLICT"
  | "SALES_REPOSITORY_UNAVAILABLE"
  | "SALES_INVENTORY_UNAVAILABLE"
  | "SALES_FISCAL_PREPARATION_INVALID"
  | "SALES_FISCAL_TAX_UNRESOLVED"
  | "SALES_RECEIVABLE_INVALID"
  | "SALES_RECEIVABLE_PAYMENT_INVALID"
  | "SALES_RECEIVABLE_PAYMENT_EXCEEDS_BALANCE"
  | "SALES_RECEIVABLE_IDEMPOTENCY_CONFLICT"
  | "SALES_BRANCH_INVALID"
  | "SALES_BRANCH_NOT_FOUND"
  | "SALES_BRANCH_ACCESS_DENIED"
  | "SALES_BRANCH_IMMUTABLE"
  | "SALES_OFFLINE_DRAFT_INVALID"
  | "SALES_OFFLINE_DRAFT_IDEMPOTENCY_CONFLICT"
  | "SALES_OFFLINE_DRAFT_LEASE_CONFLICT"
  | "SALES_OFFLINE_DRAFT_PAYLOAD_UNAVAILABLE"
  | "SALES_OFFLINE_DRAFT_STORAGE_UNAVAILABLE";

export class SalesFailure extends Error {
  /**
   * Creates an expected sales failure.
   * @param code Stable machine-readable failure code.
   * @param message Safe diagnostic message.
   * @param options Optional underlying cause.
   */
  constructor(readonly code: SalesFailureCode, message: string, options?: ErrorOptions) {
    super(message, options);
    this.name = "SalesFailure";
  }
}
