import { createClient, type SupabaseClient } from "@supabase/supabase-js";
import type { DocumentsRepository, DocumentStorage } from "@kontave/documents-application";
import { companyId } from "@kontave/companies-domain";
import { DocumentsFailure, documentFolderId, documentId } from "@kontave/documents-domain";
import { organizationId, userId, type OrganizationId } from "@kontave/organizations-domain";
import { z } from "zod";

const folderRow=z.object({id:z.string(),organization_id:z.string(),company_id:z.string().nullable(),parent_id:z.string().nullable(),name:z.string(),created_by:z.string(),version:z.number().int().positive(),created_at:z.string(),updated_at:z.string()});
const documentRow=z.object({id:z.string(),organization_id:z.string(),company_id:z.string().nullable(),folder_id:z.string().nullable(),name:z.string(),storage_path:z.string(),mime_type:z.string().nullable(),size_bytes:z.union([z.number(),z.string()]).nullable(),uploaded_by:z.string(),version:z.number().int().positive(),created_at:z.string(),updated_at:z.string()});
export interface DocumentsSupabaseConfiguration{readonly url:string;readonly serviceRoleKey:string}
export function createDocumentsInfrastructure(configuration:DocumentsSupabaseConfiguration){const client=createClient(configuration.url,configuration.serviceRoleKey,{auth:{persistSession:false,autoRefreshToken:false,detectSessionInUrl:false}});return{repository:new SupabaseDocumentsRepository(client),storage:new SupabaseDocumentStorage(client)}}

class SupabaseDocumentsRepository implements DocumentsRepository{
 constructor(private readonly client:SupabaseClient){}
 async listDocuments(input:Parameters<DocumentsRepository["listDocuments"]>[0]){const{data,error}=await this.client.rpc("list_documents_native",{p_organization_id:input.organizationId,p_company_id:input.companyId,p_filter_company:"companyId"in input,p_folder_id:input.folderId,p_filter_folder:"folderId"in input});if(error)throw failure(error);return documentRow.array().parse(data??[]).map(mapDocument)}
 async listFolders(input:Parameters<DocumentsRepository["listFolders"]>[0]){const{data,error}=await this.client.rpc("list_document_folders_native",{p_organization_id:input.organizationId,p_company_id:input.companyId,p_filter_company:"companyId"in input});if(error)throw failure(error);return folderRow.array().parse(data??[]).map(mapFolder)}
 async createFolder(input:Parameters<DocumentsRepository["createFolder"]>[0]){const{data,error}=await this.client.rpc("create_document_folder_native",{p_organization_id:input.organizationId,p_company_id:input.companyId,p_parent_id:input.parentId,p_name:input.name,p_created_by:input.createdBy}).single();if(error)throw failure(error);return mapFolder(folderRow.parse(data))}
 async renameFolder(input:Parameters<DocumentsRepository["renameFolder"]>[0]){const{data,error}=await this.client.rpc("rename_document_folder_native",{p_organization_id:input.organizationId,p_folder_id:input.folderId,p_name:input.name,p_expected_version:input.expectedVersion}).single();if(error)throw failure(error);return mapFolder(folderRow.parse(data))}
 async deleteFolder(input:Parameters<DocumentsRepository["deleteFolder"]>[0]){const{error}=await this.client.rpc("delete_document_folder_native",{p_organization_id:input.organizationId,p_folder_id:input.folderId,p_expected_version:input.expectedVersion});if(error)throw failure(error)}
 async registerDocument(input:Parameters<DocumentsRepository["registerDocument"]>[0]){const{data,error}=await this.client.rpc("register_document_native",{p_organization_id:input.organizationId,p_company_id:input.companyId,p_folder_id:input.folderId,p_name:input.name,p_storage_path:input.file.storageKey,p_mime_type:input.file.contentType,p_size_bytes:input.file.sizeBytes,p_uploaded_by:input.uploadedBy}).single();if(error)throw failure(error);return mapDocument(documentRow.parse(data))}
 async moveDocument(input:Parameters<DocumentsRepository["moveDocument"]>[0]){const{data,error}=await this.client.rpc("move_document_native",{p_organization_id:input.organizationId,p_document_id:input.documentId,p_folder_id:input.folderId,p_expected_version:input.expectedVersion}).single();if(error)throw failure(error);return mapDocument(documentRow.parse(data))}
 async findDocument(org:OrganizationId,id:ReturnType<typeof documentId>){const{data,error}=await this.client.from("shared_documents").select("id,organization_id,company_id,folder_id,name,storage_path,mime_type,size_bytes,uploaded_by,version,created_at,updated_at").eq("organization_id",org).eq("id",id).maybeSingle();if(error)throw failure(error);return data?mapDocument(documentRow.parse(data)):null}
 async deleteDocument(input:Parameters<DocumentsRepository["deleteDocument"]>[0]){const{error}=await this.client.rpc("delete_document_native",{p_organization_id:input.organizationId,p_document_id:input.documentId,p_expected_version:input.expectedVersion});if(error)throw failure(error)}
}
class SupabaseDocumentStorage implements DocumentStorage{
 constructor(private readonly client:SupabaseClient){}
 async createUpload(input:{organizationId:OrganizationId;fileName:string}){const root=await this.storageRoot(input.organizationId),safe=input.fileName.replace(/[^a-zA-Z0-9._-]/g,"_"),storageKey=`${root}/${crypto.randomUUID()}/${safe}`;const{data,error}=await this.client.storage.from("tenant-documents").createSignedUploadUrl(storageKey);if(error)throw storageFailure(error);return{uploadUrl:data.signedUrl,storageKey:data.path}}
 async createDownload(storageKey:string){const{data,error}=await this.client.storage.from("tenant-documents").createSignedUrl(storageKey,60);if(error)throw storageFailure(error);return data.signedUrl}
 async delete(storageKey:string){const{error}=await this.client.storage.from("tenant-documents").remove([storageKey]);if(error)throw storageFailure(error)}
 private async storageRoot(id:OrganizationId){const{data,error}=await this.client.from("organizations").select("legacy_tenant_id").eq("id",id).single();if(error)throw storageFailure(error);return String(data.legacy_tenant_id??id)}
}
function mapFolder(r:z.infer<typeof folderRow>){return{id:documentFolderId(r.id),organizationId:organizationId(r.organization_id),companyId:r.company_id?companyId(r.company_id):null,parentId:r.parent_id?documentFolderId(r.parent_id):null,name:r.name,createdBy:userId(r.created_by),version:r.version,createdAt:r.created_at,updatedAt:r.updated_at}}
function mapDocument(r:z.infer<typeof documentRow>){return{id:documentId(r.id),organizationId:organizationId(r.organization_id),companyId:r.company_id?companyId(r.company_id):null,folderId:r.folder_id?documentFolderId(r.folder_id):null,name:r.name,file:{storageKey:r.storage_path,contentType:r.mime_type,sizeBytes:r.size_bytes===null?null:Number(r.size_bytes)},uploadedBy:userId(r.uploaded_by),version:r.version,createdAt:r.created_at,updatedAt:r.updated_at}}
function failure(cause:{message?:string}){const message=cause.message??"";for(const[code,label]of[["DOCUMENT_FOLDER_VERSION_CONFLICT","La carpeta cambió en otro cliente."],["DOCUMENT_FOLDER_NOT_EMPTY","La carpeta contiene documentos."],["DOCUMENT_FOLDER_NOT_FOUND","La carpeta no existe."],["DOCUMENT_VERSION_CONFLICT","El documento cambió en otro cliente."],["DOCUMENT_NOT_FOUND","El documento no existe."],["DOCUMENT_OUTSIDE_COMPANY","La carpeta y el documento pertenecen a ámbitos diferentes."],["DOCUMENT_INVALID","Los datos del documento no son válidos."]]as const)if(message.includes(code))return new DocumentsFailure(code,label);return new DocumentsFailure("DOCUMENT_REPOSITORY_UNAVAILABLE","No se pudo acceder a los documentos.",{cause})}
function storageFailure(cause:unknown){return new DocumentsFailure("DOCUMENT_STORAGE_UNAVAILABLE","No se pudo acceder al archivo.",{cause})}
