import{createClient,type SupabaseClient}from"@supabase/supabase-js";
import{InventoryDashboardFailure,type InventoryDashboardQuery,type InventoryDashboardReader,type InventoryDashboardSnapshot}from"@kontave/inventory-application";
import{z}from"zod";
const amount=z.object({amount:z.string(),currency:z.literal("VES")});
const quantity=z.object({unit:z.string(),inbound:z.string(),outbound:z.string()});
const document=z.object({id:z.string(),recordType:z.enum(["invoice","delivery_note","debit_note","credit_note","other"]),number:z.string(),counterparty:z.string().nullable(),date:z.string(),status:z.string(),total:amount,transactionCurrency:z.string(),sourceTotal:z.string().nullable()});
const snapshotSchema=z.object({period:z.object({from:z.string(),to:z.string(),granularity:z.literal("day")}),summary:z.object({inboundValue:amount,outboundValue:amount,movementCount:z.number().int().nonnegative(),inventoryValue:amount,quantities:z.array(quantity),valuationDate:z.string()}),charts:z.array(z.object({date:z.string(),inboundValue:amount,outboundValue:amount,movementCount:z.number().int().nonnegative(),quantities:z.array(quantity)})),recentSales:z.array(document),recentPurchases:z.array(document),generatedAt:z.string()});
export class SupabaseInventoryDashboardReader implements InventoryDashboardReader{
 constructor(private readonly client:SupabaseClient){}
 async read(query:InventoryDashboardQuery):Promise<InventoryDashboardSnapshot>{const{data,error}=await this.client.rpc("get_shared_inventory_dashboard_snapshot",{p_actor_user_id:query.actorUserId,p_organization_id:query.organizationId,p_company_id:query.companyId,p_from:query.from,p_to:query.to,p_granularity:query.granularity,p_recent_limit:query.recentLimit});if(error){if(error.message.includes("INVENTORY_DASHBOARD_ACCESS_DENIED"))throw new InventoryDashboardFailure("INVENTORY_DASHBOARD_ACCESS_DENIED","Inventory dashboard access was denied.");if(error.message.includes("INVENTORY_DASHBOARD_INVALID"))throw new InventoryDashboardFailure("INVENTORY_DASHBOARD_INVALID","Inventory dashboard query is invalid.");throw new InventoryDashboardFailure("INVENTORY_DASHBOARD_UNAVAILABLE","Inventory dashboard is unavailable.",{cause:error});}const parsed=snapshotSchema.safeParse(data);if(!parsed.success)throw new InventoryDashboardFailure("INVENTORY_DASHBOARD_UNAVAILABLE","Inventory dashboard returned invalid data.",{cause:parsed.error});return parsed.data;}
}
export function createSupabaseInventoryDashboardReader(configuration:{readonly url:string;readonly serviceRoleKey:string}){return new SupabaseInventoryDashboardReader(createClient(configuration.url,configuration.serviceRoleKey,{auth:{persistSession:false,autoRefreshToken:false,detectSessionInUrl:false}}));}
