import{createClient,type SupabaseClient}from"@supabase/supabase-js";
import{InventoryDashboardFailure,type InventoryDashboardQuery,type InventoryDashboardReader,type InventoryDashboardSnapshot}from"@kontave/inventory-application";
import{z}from"zod";
import{companyId}from"@kontave/companies-domain";import{ReplenishmentPolicy,InventoryFailure}from"@kontave/inventory-domain";import{productId,UnitOfMeasure}from"@kontave/products-domain";import type{ReplenishmentPolicyRepository}from"@kontave/inventory-application";
import{SupabaseInventoryOperationsRepository}from"./inventory-operations";
export * from "./inventory-operations";
const amount=z.object({amount:z.string(),currency:z.literal("VES")});
const quantity=z.object({unit:z.string(),inbound:z.string(),outbound:z.string()});
const document=z.object({id:z.string(),recordType:z.enum(["invoice","delivery_note","debit_note","credit_note","other"]),number:z.string(),counterparty:z.string().nullable(),date:z.string(),status:z.string(),total:amount,transactionCurrency:z.string(),sourceTotal:z.string().nullable()});
const recentMovement=z.object({id:z.string(),productId:z.string(),productName:z.string(),productSku:z.string(),effectiveDate:z.string(),movementType:z.string(),direction:z.enum(["inbound","outbound"]),quantity:z.object({value:z.string(),unit:z.nativeEnum(UnitOfMeasure)}),totalCost:amount,reference:z.string().nullable()});
const snapshotSchema=z.object({period:z.object({from:z.string(),to:z.string(),granularity:z.literal("day")}),summary:z.object({inboundValue:amount,outboundValue:amount,movementCount:z.number().int().nonnegative(),inventoryValue:amount,quantities:z.array(quantity),valuationDate:z.string()}),charts:z.array(z.object({date:z.string(),inboundValue:amount,outboundValue:amount,movementCount:z.number().int().nonnegative(),quantities:z.array(quantity)})),recentSales:z.array(document),recentPurchases:z.array(document),recentInboundMovements:z.array(recentMovement),recentOutboundMovements:z.array(recentMovement),generatedAt:z.string()});
export class SupabaseInventoryDashboardReader implements InventoryDashboardReader{
 constructor(private readonly client:SupabaseClient){}
 async read(query:InventoryDashboardQuery):Promise<InventoryDashboardSnapshot>{const{data,error}=await this.client.rpc("get_shared_inventory_dashboard_snapshot",{p_actor_user_id:query.actorUserId,p_organization_id:query.organizationId,p_company_id:query.companyId,p_from:query.from,p_to:query.to,p_granularity:query.granularity,p_recent_limit:query.recentLimit});if(error){if(error.message.includes("INVENTORY_DASHBOARD_ACCESS_DENIED"))throw new InventoryDashboardFailure("INVENTORY_DASHBOARD_ACCESS_DENIED","Inventory dashboard access was denied.");if(error.message.includes("INVENTORY_DASHBOARD_INVALID"))throw new InventoryDashboardFailure("INVENTORY_DASHBOARD_INVALID","Inventory dashboard query is invalid.");throw new InventoryDashboardFailure("INVENTORY_DASHBOARD_UNAVAILABLE","Inventory dashboard is unavailable.",{cause:error});}const parsed=snapshotSchema.safeParse(data);if(!parsed.success)throw new InventoryDashboardFailure("INVENTORY_DASHBOARD_UNAVAILABLE","Inventory dashboard returned invalid data.",{cause:parsed.error});return parsed.data;}
}
export function createSupabaseInventoryDashboardReader(configuration:{readonly url:string;readonly serviceRoleKey:string}){return new SupabaseInventoryDashboardReader(createClient(configuration.url,configuration.serviceRoleKey,{auth:{persistSession:false,autoRefreshToken:false,detectSessionInUrl:false}}));}
export class SupabaseReplenishmentPolicyRepository implements ReplenishmentPolicyRepository{constructor(private readonly client:SupabaseClient){}async update(input:Parameters<ReplenishmentPolicyRepository["update"]>[0]){const{data,error}=await this.client.rpc("update_native_replenishment_policy",{p_actor_user_id:input.actorUserId,p_organization_id:input.organizationId,p_company_id:input.companyId,p_product_id:input.productId,p_minimum_quantity:input.minimumQuantity,p_expected_version:input.expectedVersion});if(error)throw new InventoryFailure(error.message.includes("INVENTORY_PROFILE_VERSION_CONFLICT")?"INVENTORY_PROFILE_VERSION_CONFLICT":"INVENTORY_REPOSITORY_UNAVAILABLE",error.message,{cause:error});const parsed=z.object({companyId:z.string(),productId:z.string(),unit:z.nativeEnum(UnitOfMeasure),minimumQuantity:z.string().nullable(),version:z.number().int().positive(),updatedAt:z.string()}).parse(data);return new ReplenishmentPolicy({...parsed,companyId:companyId(parsed.companyId),productId:productId(parsed.productId)});}}
export function createSupabaseReplenishmentPolicyRepository(configuration:{readonly url:string;readonly serviceRoleKey:string}){return new SupabaseReplenishmentPolicyRepository(createClient(configuration.url,configuration.serviceRoleKey,{auth:{persistSession:false,autoRefreshToken:false,detectSessionInUrl:false}}));}
export function createSupabaseInventoryOperationsRepository(configuration:{readonly url:string;readonly serviceRoleKey:string}){return new SupabaseInventoryOperationsRepository(createClient(configuration.url,configuration.serviceRoleKey,{auth:{persistSession:false,autoRefreshToken:false,detectSessionInUrl:false}}));}
