import { createClient, type SupabaseClient } from "@supabase/supabase-js";
import { SalesDashboardFailure, type SalesDashboardQuery, type SalesDashboardReader, type SalesDashboardSnapshot } from "@kontave/sales-application";
import { z } from "zod";
const money=z.object({amount:z.string(),currency:z.literal("VES")});
const document=z.object({id:z.string(),sourceKind:z.literal("legacy_sales_invoice"),documentType:z.literal("invoice"),invoiceNumber:z.string(),customerName:z.string().nullable(),date:z.string(),status:z.enum(["confirmed","draft"]),salesChannel:z.enum(["administrative","pos"]),subtotal:money,taxableBase:money,vatAmount:money,total:money,transactionCurrency:z.string(),sourceSubtotal:z.string().nullable(),sourceVatAmount:z.string().nullable(),sourceTotal:z.string().nullable()});
const snapshot=z.object({period:z.object({from:z.string(),to:z.string(),granularity:z.literal("day")}),summary:z.object({confirmedInvoicedAmount:money,taxableBaseAmount:money,vatDebitAmount:money,confirmedInvoiceCount:z.number().int().nonnegative(),draftInvoiceCount:z.number().int().nonnegative(),averageTicketAmount:money}),charts:z.array(z.object({date:z.string(),confirmedInvoicedAmount:money,taxableBaseAmount:money,vatDebitAmount:money,confirmedInvoiceCount:z.number().int().nonnegative()})),recentConfirmedInvoices:z.array(document),recentDraftInvoices:z.array(document),generatedAt:z.string()});
/** Legacy shared-table knowledge is confined to this compatibility adapter. */
export class SupabaseSalesDashboardReader implements SalesDashboardReader{
 constructor(private readonly client:SupabaseClient){}
 async read(query:SalesDashboardQuery):Promise<SalesDashboardSnapshot>{const{data,error}=await this.client.rpc("get_native_sales_dashboard_snapshot",{p_actor_user_id:query.actorUserId,p_organization_id:query.organizationId,p_company_id:query.companyId,p_from:query.from,p_to:query.to,p_granularity:query.granularity,p_recent_limit:query.recentLimit});if(error){if(error.message.includes("SALES_DASHBOARD_ACCESS_DENIED"))throw new SalesDashboardFailure("SALES_DASHBOARD_ACCESS_DENIED","Sales dashboard access was denied.");if(error.message.includes("SALES_DASHBOARD_INVALID"))throw new SalesDashboardFailure("SALES_DASHBOARD_INVALID","Sales dashboard query is invalid.");throw new SalesDashboardFailure("SALES_DASHBOARD_UNAVAILABLE","Sales dashboard is unavailable.",{cause:error});}const parsed=snapshot.safeParse(data);if(!parsed.success)throw new SalesDashboardFailure("SALES_DASHBOARD_UNAVAILABLE","Sales dashboard returned invalid data.",{cause:parsed.error});return parsed.data;}
}
export function createSupabaseSalesDashboardReader(configuration:{readonly url:string;readonly serviceRoleKey:string}):SalesDashboardReader{return new SupabaseSalesDashboardReader(createClient(configuration.url,configuration.serviceRoleKey,{auth:{persistSession:false,autoRefreshToken:false,detectSessionInUrl:false}}));}
