import type{CompanyId}from"@kontave/companies-domain";import type{OrganizationId,UserId}from"@kontave/organizations-domain";import type{ProductId,UnitOfMeasure}from"@kontave/products-domain";
export type ProductInsightGranularity="day"|"week"|"month";
export interface ProductInsightsQuery{readonly actorUserId:UserId;readonly organizationId:OrganizationId;readonly companyId:CompanyId;readonly productId:ProductId;readonly from:string;readonly to:string;readonly granularity:ProductInsightGranularity}
export interface UnitValueObservation{readonly effectiveDate:string;readonly sourceUnitAmount:{readonly amount:string;readonly currency:string};readonly unitAmount:{readonly amount:string;readonly currency:"VES"};readonly exchangeRate:string|null;readonly quantity:{readonly value:string;readonly unit:UnitOfMeasure};readonly reference:string|null;readonly documentId:string}
export interface UnitEconomicsAggregate{readonly weightedAverageUnitAmount:{readonly amount:string;readonly currency:"VES"};readonly quantity:{readonly value:string;readonly unit:UnitOfMeasure};readonly observations:number}
export interface ProductUnitEconomics{readonly period:{readonly from:string;readonly to:string;readonly granularity:ProductInsightGranularity};readonly latestAcquisition:UnitValueObservation|null;readonly points:readonly{readonly bucketStart:string;readonly acquisition:UnitEconomicsAggregate|null;readonly realizedSale:UnitEconomicsAggregate|null}[];readonly coverage:{readonly confirmedAcquisitions:number;readonly confirmedSales:number;readonly legacyRecordedOutboundPrices:number};readonly generatedAt:string}
export class ProductInsightsFailure extends Error{constructor(readonly code:"PRODUCT_INSIGHTS_INVALID"|"PRODUCT_INSIGHTS_NOT_FOUND"|"PRODUCT_INSIGHTS_ACCESS_DENIED"|"PRODUCT_INSIGHTS_UNAVAILABLE",message:string,options?:ErrorOptions){super(message,options);this.name="ProductInsightsFailure";}}
export interface ProductInsightsReader{read(query:ProductInsightsQuery):Promise<ProductUnitEconomics>}
export class GetProductUnitEconomics{constructor(private readonly reader:ProductInsightsReader){}execute(query:ProductInsightsQuery){return this.reader.read(validate(query));}}
function validate(query:ProductInsightsQuery):ProductInsightsQuery{date(query.from);date(query.to);if(query.from>query.to)invalid("Insight start date must not be after its end date.");const days=Math.floor((Date.parse(`${query.to}T00:00:00Z`)-Date.parse(`${query.from}T00:00:00Z`))/86400000)+1;if(days>366)invalid("Product insight periods cannot exceed 366 days.");if(!["day","week","month"].includes(query.granularity))invalid("Product insight granularity is invalid.");return query;}
function date(value:string){if(!/^\d{4}-\d{2}-\d{2}$/.test(value))invalid("Product insight dates must use YYYY-MM-DD.");const[year,month,day]=value.split("-").map(Number)as[number,number,number],parsed=new Date(Date.UTC(year,month-1,day));if(parsed.getUTCFullYear()!==year||parsed.getUTCMonth()!==month-1||parsed.getUTCDate()!==day)invalid("Product insight date is invalid.");}
function invalid(message:string):never{throw new ProductInsightsFailure("PRODUCT_INSIGHTS_INVALID",message);}
