export type InventoryFailureCode =
  | "INVENTORY_IDENTIFIER_INVALID"
  | "INVENTORY_DATE_INVALID"
  | "INVENTORY_QUANTITY_INVALID"
  | "INVENTORY_QUANTITY_UNIT_MISMATCH"
  | "INVENTORY_PROFILE_INVALID"
  | "INVENTORY_PROFILE_VERSION_CONFLICT"
  | "INVENTORY_PROFILE_INACTIVE"
  | "INVENTORY_LOCATION_INVALID"
  | "INVENTORY_LOT_INVALID"
  | "INVENTORY_LOT_REQUIRED"
  | "INVENTORY_LOT_NOT_ALLOWED"
  | "INVENTORY_LOT_UNAVAILABLE"
  | "INVENTORY_OPERATION_INVALID"
  | "INVENTORY_OPERATION_TRANSITION_INVALID"
  | "INVENTORY_TRANSFER_UNBALANCED"
  | "INVENTORY_SOURCE_DUPLICATE"
  | "INVENTORY_POSITION_MISMATCH"
  | "INVENTORY_NEGATIVE_STOCK"
  | "INVENTORY_PERIOD_CLOSED"
  | "INVENTORY_COUNT_INVALID"
  | "INVENTORY_VALUATION_INVALID"
  | "INVENTORY_VALUATION_METHOD_UNSUPPORTED"
  | "INVENTORY_CURRENCY_MISMATCH"
  | "INVENTORY_REPOSITORY_UNAVAILABLE";

export class InventoryFailure extends Error {
  constructor(readonly code: InventoryFailureCode, message: string, options?: ErrorOptions) {
    super(message, options);
    this.name = "InventoryFailure";
  }
}
