import type { ProductCategoryOverviewItem,ProductCategoryOverviewPage,ProductCursorPage,ProductDetail } from "@kontave/products-application";
import type { ProductCategory } from "@kontave/products-domain";
import type { NativeProductCategoryDto,NativeProductCategoryOverviewDto,NativeProductCategoryOverviewItemDto,NativeProductDetailDto,NativeProductDto,NativeProductListDto } from "@kontave/native-api-contracts";
import type{ProductSalePricing}from"@kontave/pricing-domain";import type{ResolvedProductTaxation}from"@kontave/taxation-application";
export function toNativeProductCategoryDto(value:ProductCategory):NativeProductCategoryDto{return{id:value.id,name:value.name,description:value.description,status:value.status,version:value.version};}
export function toNativeProductCategoryOverviewItemDto(value:ProductCategoryOverviewItem):NativeProductCategoryOverviewItemDto{return{...toNativeProductCategoryDto(value.category),productCount:value.productCount,createdAt:value.createdAt,updatedAt:value.updatedAt};}
export function toNativeProductCategoryOverviewDto(value:ProductCategoryOverviewPage):NativeProductCategoryOverviewDto{return{...value,items:value.items.map(toNativeProductCategoryOverviewItemDto)};}
export function toNativeProductDto(value:ProductDetail):NativeProductDto{return{id:value.product.id,sku:value.product.sku,barcodes:value.product.barcodes,name:value.product.name,description:value.product.description,category:value.category?toNativeProductCategoryDto(value.category):null,baseUnit:value.product.baseUnit,status:value.product.status,inventory:value.inventory,updatedAt:value.updatedAt,version:value.product.version};}
export function toNativeProductDetailDto(value:ProductDetail,commercial?:{readonly pricing:ProductSalePricing;readonly taxation:ResolvedProductTaxation}):NativeProductDetailDto{const taxation=commercial?.taxation,treatment=taxation?.assignment.treatment;return{...toNativeProductDto(value),salePricing:commercial?{policy:commercial.pricing.policy,version:commercial.pricing.version,updatedAt:commercial.pricing.updatedAt}:null,taxation:taxation?{profileId:taxation.profile.id,taxCode:taxation.assignment.taxCode,treatment:taxation.assignment.treatment,resolvedRate:taxation.rule.rate,effectiveFrom:taxation.assignment.effectiveFrom,effectiveTo:taxation.assignment.effectiveTo,legalBasis:taxation.assignment.legalBasis,ruleVersion:`${taxation.assignment.classificationVersion}|${taxation.rule.version}`,version:taxation.profile.version}:null,productType:"merchandise",valuationMethod:"weighted_average",vat:taxation&&(treatment==="taxed"||treatment==="exempt")?{code:treatment==="exempt"?"exempt":"general",rate:taxation.rule.rate}:null,capabilities:{...value.capabilities,salePricing:commercial!==undefined,vatConfiguration:taxation!==undefined,valuationMethodChange:false}};}
export function toNativeProductListDto(value:ProductCursorPage):NativeProductListDto{return{items:value.items.map(item=>toNativeProductDto({...item,capabilities:{inventoryEnabled:item.inventory!==null,locationTracking:false,lotTracking:false}})),nextCursor:value.nextCursor,total:value.total,summary:value.summary};}
