-- Portable commercial product capabilities. Web keeps using its legacy columns;
-- native adapters receive independent versions and truthful confirmed facts.
alter table public.shared_inventory_products add column if not exists sale_pricing_version integer not null default 1 check(sale_pricing_version>0);
alter table public.shared_inventory_products add column if not exists sale_pricing_updated_at timestamptz not null default now();

create table if not exists public.shared_product_tax_profiles(
 tenant_id uuid not null references public.tenants(id) on delete cascade,id text not null,company_id text not null,product_id text not null,
 jurisdiction varchar(16) not null,version integer not null default 1 check(version>0),created_at timestamptz not null default now(),updated_at timestamptz not null default now(),
 primary key(tenant_id,id),unique(tenant_id,product_id),foreign key(tenant_id,company_id)references public.shared_companies(tenant_id,id)on delete cascade,
 foreign key(tenant_id,product_id)references public.shared_inventory_products(tenant_id,id)on delete cascade
);
create table if not exists public.shared_product_tax_assignments(
 tenant_id uuid not null references public.tenants(id)on delete cascade,id text not null,profile_id text not null,tax_code varchar(64)not null,treatment text not null,
 effective_from date not null,effective_to date,legal_basis text not null,classification_version text not null,created_at timestamptz not null default now(),
 primary key(tenant_id,id),foreign key(tenant_id,profile_id)references public.shared_product_tax_profiles(tenant_id,id)on delete cascade,
 check(treatment in('taxed','exempt','exonerated','not_subject')),check(effective_to is null or effective_to>=effective_from)
);
create unique index if not exists shared_product_tax_assignment_open_idx on public.shared_product_tax_assignments(tenant_id,profile_id,tax_code)where effective_to is null;
create index if not exists shared_product_tax_assignment_period_idx on public.shared_product_tax_assignments(tenant_id,profile_id,tax_code,effective_from,effective_to);
create table if not exists public.shared_tax_rules(
 id text primary key,tax_code varchar(64)not null,jurisdiction varchar(16)not null,treatment text not null,rate numeric(12,6)not null,calculation_mode text not null,
 effective_from date not null,effective_to date,legal_basis text not null,version text not null,created_at timestamptz not null default now(),
 check(treatment in('taxed','exempt','exonerated','not_subject')),check(calculation_mode in('tax_exclusive','tax_inclusive')),check(effective_to is null or effective_to>=effective_from)
);
insert into public.shared_tax_rules(id,tax_code,jurisdiction,treatment,rate,calculation_mode,effective_from,effective_to,legal_basis,version)values
 ('legacy-ve-iva-taxed-16','IVA','VE','taxed',16,'tax_exclusive','2000-01-01',null,'Migrated production rule; requires legal catalogue review.','legacy-production-1'),
 ('legacy-ve-iva-exempt-0','IVA','VE','exempt',0,'tax_exclusive','2000-01-01',null,'Migrated production classification; requires legal catalogue review.','legacy-production-1')
on conflict(id)do nothing;

insert into public.shared_product_tax_profiles(tenant_id,id,company_id,product_id,jurisdiction,version)
select p.tenant_id,'legacy:'||p.id,p.company_id,p.id,'VE',1 from public.shared_inventory_products p on conflict(tenant_id,product_id)do nothing;
insert into public.shared_product_tax_assignments(tenant_id,id,profile_id,tax_code,treatment,effective_from,effective_to,legal_basis,classification_version)
select p.tenant_id,'legacy:'||p.id||':iva','legacy:'||p.id,'IVA',case when p.vat_type='exento'then'exempt'else'taxed'end,
 least(p.created_at::date,current_date),null,'Migrated from the production product IVA classification.','legacy-product-1'
from public.shared_inventory_products p where not exists(select 1 from public.shared_product_tax_assignments a where a.tenant_id=p.tenant_id and a.profile_id='legacy:'||p.id and a.tax_code='IVA');

alter table public.shared_product_tax_profiles enable row level security;alter table public.shared_product_tax_assignments enable row level security;alter table public.shared_tax_rules enable row level security;
create policy shared_product_tax_profiles_member_access on public.shared_product_tax_profiles for select to authenticated using(exists(select 1 from public.tenant_memberships m where m.tenant_id=shared_product_tax_profiles.tenant_id and m.member_id=auth.uid()and m.accepted_at is not null and m.revoked_at is null));
create policy shared_product_tax_assignments_member_access on public.shared_product_tax_assignments for select to authenticated using(exists(select 1 from public.tenant_memberships m where m.tenant_id=shared_product_tax_assignments.tenant_id and m.member_id=auth.uid()and m.accepted_at is not null and m.revoked_at is null));
create policy shared_tax_rules_read on public.shared_tax_rules for select to authenticated using(true);

create or replace function public.get_native_product_sale_pricing(p_actor_user_id uuid,p_organization_id uuid,p_company_id text,p_product_id text)
returns jsonb language plpgsql stable security definer set search_path=public as $$declare v_tenant uuid;begin v_tenant:=public.native_products_assert_access(p_actor_user_id,p_organization_id,p_company_id);return(select jsonb_build_object('companyId',company_id,'productId',id,'policy',case when sale_price_mode is null then null when sale_price_mode='fixed'then jsonb_build_object('mode','fixed','amount',sale_price_value::text,'currency',sale_price_currency_code)else jsonb_build_object('mode','markup','percentage',sale_price_value::text,'currency',sale_price_currency_code)end,'version',sale_pricing_version,'updatedAt',sale_pricing_updated_at)from public.shared_inventory_products where tenant_id=v_tenant and company_id=p_company_id and id=p_product_id);end$$;
create or replace function public.save_native_product_sale_pricing(p_actor_user_id uuid,p_organization_id uuid,p_company_id text,p_product_id text,p_policy jsonb,p_expected_version integer)
returns jsonb language plpgsql security definer set search_path=public as $$declare v_tenant uuid;v_found integer;v_mode text;v_value numeric;v_currency text;begin
 v_tenant:=public.native_products_assert_access(p_actor_user_id,p_organization_id,p_company_id);v_mode:=p_policy->>'mode';v_currency:=upper(p_policy->>'currency');v_value:=case when v_mode='fixed'then(p_policy->>'amount')::numeric when v_mode='markup'then(p_policy->>'percentage')::numeric else null end;
 if p_policy is not null and(v_mode not in('fixed','markup')or v_currency!~'^[A-Z]{3}$'or v_value<0 or(v_mode='fixed'and v_value=0))then raise exception'PRICING_INVALID';end if;
 update public.shared_inventory_products set sale_price_mode=case when p_policy is null then null else v_mode end,sale_price_value=case when p_policy is null then null else v_value end,sale_price_currency_code=case when p_policy is null then null else v_currency end,sale_price_currency=case when p_policy is null then null when v_currency='VES'then'B'when v_currency='USD'then'D'else null end,sale_pricing_version=sale_pricing_version+1,sale_pricing_updated_at=now()
 where tenant_id=v_tenant and company_id=p_company_id and id=p_product_id and sale_pricing_version=p_expected_version;get diagnostics v_found=row_count;
 if v_found=0 then if exists(select 1 from public.shared_inventory_products where tenant_id=v_tenant and company_id=p_company_id and id=p_product_id)then raise exception'PRICING_VERSION_CONFLICT';else raise exception'PRICING_PRODUCT_NOT_FOUND';end if;end if;
 return public.get_native_product_sale_pricing(p_actor_user_id,p_organization_id,p_company_id,p_product_id);exception when invalid_text_representation then raise exception'PRICING_INVALID';end$$;

create or replace function public.native_product_tax_profile_json(p_tenant uuid,p_company_id text,p_product_id text)returns jsonb language sql stable set search_path=public as $$select jsonb_build_object('id',pr.id,'companyId',pr.company_id,'productId',pr.product_id,'jurisdiction',pr.jurisdiction,'version',pr.version,'assignments',coalesce((select jsonb_agg(jsonb_build_object('taxCode',a.tax_code,'treatment',a.treatment,'effectiveFrom',a.effective_from,'effectiveTo',a.effective_to,'legalBasis',a.legal_basis,'classificationVersion',a.classification_version)order by a.effective_from)from public.shared_product_tax_assignments a where a.tenant_id=pr.tenant_id and a.profile_id=pr.id),'[]'::jsonb))from public.shared_product_tax_profiles pr where pr.tenant_id=p_tenant and pr.company_id=p_company_id and pr.product_id=p_product_id$$;
create or replace function public.get_native_product_tax_profile(p_actor_user_id uuid,p_organization_id uuid,p_company_id text,p_product_id text)returns jsonb language plpgsql stable security definer set search_path=public as $$declare v_tenant uuid;begin v_tenant:=public.native_products_assert_access(p_actor_user_id,p_organization_id,p_company_id);return public.native_product_tax_profile_json(v_tenant,p_company_id,p_product_id);end$$;
create or replace function public.list_native_tax_rules(p_tax_code text,p_jurisdiction text)returns jsonb language sql stable security definer set search_path=public as $$select coalesce(jsonb_agg(jsonb_build_object('id',id,'taxCode',tax_code,'jurisdiction',jurisdiction,'treatment',treatment,'rate',rate::text,'calculationMode',calculation_mode,'effectiveFrom',effective_from,'effectiveTo',effective_to,'legalBasis',legal_basis,'version',version)order by effective_from),'[]'::jsonb)from public.shared_tax_rules where tax_code=upper(p_tax_code)and jurisdiction=upper(p_jurisdiction)$$;
create or replace function public.set_native_product_tax_treatment(p_actor_user_id uuid,p_organization_id uuid,p_company_id text,p_product_id text,p_tax_code text,p_treatment text,p_effective_from date,p_legal_basis text,p_expected_version integer)
returns jsonb language plpgsql security definer set search_path=public as $$declare v_tenant uuid;v_profile record;v_current record;begin
 v_tenant:=public.native_products_assert_access(p_actor_user_id,p_organization_id,p_company_id);if p_treatment not in('taxed','exempt','exonerated','not_subject')or nullif(btrim(p_legal_basis),'')is null then raise exception'TAXATION_PROFILE_INVALID';end if;
 select*into v_profile from public.shared_product_tax_profiles where tenant_id=v_tenant and company_id=p_company_id and product_id=p_product_id for update;if not found then raise exception'TAXATION_PROFILE_NOT_FOUND';end if;if v_profile.version<>p_expected_version then raise exception'TAXATION_VERSION_CONFLICT';end if;
 select*into v_current from public.shared_product_tax_assignments where tenant_id=v_tenant and profile_id=v_profile.id and tax_code=upper(p_tax_code)and effective_to is null for update;
 if found and p_effective_from<v_current.effective_from then raise exception'TAXATION_PROFILE_INVALID';elsif found and p_effective_from=v_current.effective_from then update public.shared_product_tax_assignments set treatment=p_treatment,legal_basis=btrim(p_legal_basis),classification_version='native:'||(v_profile.version+1)::text where tenant_id=v_tenant and id=v_current.id;elsif found then update public.shared_product_tax_assignments set effective_to=p_effective_from-1 where tenant_id=v_tenant and id=v_current.id;insert into public.shared_product_tax_assignments values(v_tenant,gen_random_uuid()::text,v_profile.id,upper(p_tax_code),p_treatment,p_effective_from,null,btrim(p_legal_basis),'native:'||(v_profile.version+1)::text,now());else insert into public.shared_product_tax_assignments values(v_tenant,gen_random_uuid()::text,v_profile.id,upper(p_tax_code),p_treatment,p_effective_from,null,btrim(p_legal_basis),'native:'||(v_profile.version+1)::text,now());end if;
 update public.shared_product_tax_profiles set version=version+1,updated_at=now()where tenant_id=v_tenant and id=v_profile.id;update public.shared_inventory_products set vat_type=case when p_treatment='exempt'then'exento'else'general'end where tenant_id=v_tenant and id=p_product_id;
 return public.native_product_tax_profile_json(v_tenant,p_company_id,p_product_id);end$$;

create or replace function public.get_native_product_unit_economics(p_actor_user_id uuid,p_organization_id uuid,p_company_id text,p_product_id text,p_from date,p_to date,p_granularity text default'day')
returns jsonb language plpgsql stable security definer set search_path=public as $$declare v_tenant uuid;v_unit text;v_points jsonb;v_latest jsonb;v_coverage jsonb;begin
 v_tenant:=public.native_products_assert_access(p_actor_user_id,p_organization_id,p_company_id);if p_to<p_from or p_to-p_from>365 or p_granularity not in('day','week','month')then raise exception'PRODUCT_INSIGHTS_INVALID';end if;select public.native_product_unit(measure_unit)into v_unit from public.shared_inventory_products where tenant_id=v_tenant and company_id=p_company_id and id=p_product_id;if v_unit is null then raise exception'PRODUCT_INSIGHTS_NOT_FOUND';end if;
 with observations as(
  select case p_granularity when'day'then m.date when'week'then date_trunc('week',m.date)::date else date_trunc('month',m.date)::date end bucket,'acquisition'kind,m.quantity,m.unit_cost unit_amount from public.shared_inventory_movements m where m.tenant_id=v_tenant and m.company_id=p_company_id and m.product_id=p_product_id and m.type='entrada'and m.purchase_invoice_id is not null and m.date between p_from and p_to
  union all select case p_granularity when'day'then f.invoice_date when'week'then date_trunc('week',f.invoice_date)::date else date_trunc('month',f.invoice_date)::date end,'sale',i.quantity,i.unit_price from public.shared_inventory_sales_invoice_items i join public.shared_inventory_sales_invoices f on f.tenant_id=i.tenant_id and f.id=i.invoice_id where i.tenant_id=v_tenant and f.company_id=p_company_id and i.product_id=p_product_id and f.status='confirmada'and f.invoice_date between p_from and p_to
 ),buckets as(select bucket,kind,sum(quantity)quantity,sum(unit_amount*quantity)/nullif(sum(quantity),0)weighted,count(*)observations from observations group by bucket,kind),dates as(select distinct bucket from buckets)
 select coalesce(jsonb_agg(jsonb_build_object('bucketStart',d.bucket,'acquisition',case when a.bucket is null then null else jsonb_build_object('weightedAverageUnitAmount',jsonb_build_object('amount',a.weighted::text,'currency','VES'),'quantity',jsonb_build_object('value',a.quantity::text,'unit',v_unit),'observations',a.observations)end,'realizedSale',case when s.bucket is null then null else jsonb_build_object('weightedAverageUnitAmount',jsonb_build_object('amount',s.weighted::text,'currency','VES'),'quantity',jsonb_build_object('value',s.quantity::text,'unit',v_unit),'observations',s.observations)end)order by d.bucket),'[]'::jsonb)into v_points from dates d left join buckets a on a.bucket=d.bucket and a.kind='acquisition'left join buckets s on s.bucket=d.bucket and s.kind='sale';
 select jsonb_build_object('effectiveDate',m.date,'sourceUnitAmount',jsonb_build_object('amount',coalesce(m.currency_cost,m.unit_cost)::text,'currency',coalesce(m.currency,'VES')),'unitAmount',jsonb_build_object('amount',m.unit_cost::text,'currency','VES'),'exchangeRate',m.dollar_rate::text,'quantity',jsonb_build_object('value',m.quantity::text,'unit',v_unit),'reference',nullif(m.reference,''),'documentId',m.purchase_invoice_id)into v_latest from public.shared_inventory_movements m where m.tenant_id=v_tenant and m.company_id=p_company_id and m.product_id=p_product_id and m.type='entrada'and m.purchase_invoice_id is not null and m.date<=p_to order by m.date desc,m.created_at desc limit 1;
 select jsonb_build_object('confirmedAcquisitions',count(*)filter(where type='entrada'and purchase_invoice_id is not null),'confirmedSales',(select count(*)from public.shared_inventory_sales_invoice_items i join public.shared_inventory_sales_invoices f on f.tenant_id=i.tenant_id and f.id=i.invoice_id where i.tenant_id=v_tenant and f.company_id=p_company_id and i.product_id=p_product_id and f.status='confirmada'and f.invoice_date between p_from and p_to),'legacyRecordedOutboundPrices',count(*)filter(where type='salida'and sales_invoice_id is null and sale_price_unit is not null))into v_coverage from public.shared_inventory_movements where tenant_id=v_tenant and company_id=p_company_id and product_id=p_product_id and date between p_from and p_to;
 return jsonb_build_object('period',jsonb_build_object('from',p_from,'to',p_to,'granularity',p_granularity),'latestAcquisition',v_latest,'points',v_points,'coverage',v_coverage,'generatedAt',now());end$$;

do $$declare r record;begin for r in select p.oid::regprocedure signature from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public'and p.proname in('get_native_product_sale_pricing','save_native_product_sale_pricing','native_product_tax_profile_json','get_native_product_tax_profile','list_native_tax_rules','set_native_product_tax_treatment','get_native_product_unit_economics')loop execute format('revoke all on function %s from public,anon,authenticated',r.signature);execute format('grant execute on function %s to service_role',r.signature);end loop;end$$;
