-- Portable inventory operations. Source documents remain owned by purchasing/sales;
-- these tables own only drafts, posting metadata, effects, and audit reversals.
create table if not exists public.shared_inventory_operations(
 tenant_id uuid not null references public.tenants(id)on delete cascade,id text not null,company_id text not null,
 reason text not null,effective_date date not null,status text not null default'draft',source_kind text not null default'inventory',source_document_id text not null,
 reference text,notes text,version integer not null default 1,posted_at timestamptz,reversal_of text,reversed_by text,created_by uuid not null,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),
 primary key(tenant_id,id),foreign key(tenant_id,company_id)references public.shared_companies(tenant_id,id)on delete cascade,
 check(reason in('opening_balance','purchase_receipt','sales_issue','customer_return','supplier_return','transfer','stock_count_adjustment','self_consumption','production_consumption','production_output','reversal')),
 check(status in('draft','posted','reversed')),check(source_kind in('purchasing','sales','inventory','production','migration')),
 check((status='draft'and posted_at is null)or(status<>'draft'and posted_at is not null))
);
create table if not exists public.shared_inventory_operation_lines(
 tenant_id uuid not null,operation_id text not null,id text not null,product_id text not null,direction text not null,quantity numeric(14,4)not null,unit text not null,unit_cost numeric(14,4),movement_id text,
 primary key(tenant_id,id),foreign key(tenant_id,operation_id)references public.shared_inventory_operations(tenant_id,id)on delete cascade,
 foreign key(tenant_id,product_id)references public.shared_inventory_products(tenant_id,id),foreign key(tenant_id,movement_id)references public.shared_inventory_movements(tenant_id,id),
 check(direction in('inbound','outbound')),check(quantity>0)
);
create index if not exists shared_inventory_operations_company_date_idx on public.shared_inventory_operations(tenant_id,company_id,effective_date desc,id desc);
create index if not exists shared_inventory_operation_lines_movement_idx on public.shared_inventory_operation_lines(tenant_id,movement_id)where movement_id is not null;
alter table public.shared_inventory_operations enable row level security;alter table public.shared_inventory_operation_lines enable row level security;
revoke all on public.shared_inventory_operations,public.shared_inventory_operation_lines from anon,authenticated;

create or replace function public.native_inventory_legacy_reason(p_type text)returns text language sql immutable as $$select case p_type when'entrada'then'purchase_receipt'when'salida'then'sales_issue'when'devolucion_entrada'then'supplier_return'when'devolucion_salida'then'customer_return'when'autoconsumo'then'self_consumption'else'stock_count_adjustment'end$$;
create or replace function public.native_inventory_legacy_direction(p_type text)returns text language sql immutable as $$select case when p_type in('entrada','devolucion_salida','ajuste_positivo')then'inbound'else'outbound'end$$;
create or replace function public.native_inventory_legacy_type(p_reason text,p_direction text)returns text language sql immutable as $$select case when p_reason='self_consumption'then'autoconsumo'when p_reason='opening_balance'then'entrada'when p_reason='stock_count_adjustment'and p_direction='inbound'then'ajuste_positivo'when p_reason='stock_count_adjustment'then'ajuste_negativo'when p_reason='reversal'and p_direction='inbound'then'ajuste_positivo'else'ajuste_negativo'end$$;

create or replace function public.native_inventory_operation_json(p_tenant uuid,p_operation_id text)returns jsonb language sql stable set search_path=public as $$
 select jsonb_build_object('id',o.id,'companyId',o.company_id,'reason',o.reason,'effectiveDate',o.effective_date,'status',o.status,'version',o.version,
 'source',jsonb_build_object('kind',o.source_kind,'documentId',o.source_document_id),'reference',o.reference,'notes',o.notes,'postedAt',o.posted_at,'reversalOf',o.reversal_of,'reversedBy',o.reversed_by,
 'lines',coalesce((select jsonb_agg(jsonb_build_object('id',l.id,'productId',l.product_id,'productName',p.name,'productSku',p.code,'direction',l.direction,'quantity',jsonb_build_object('value',l.quantity::text,'unit',public.native_product_unit(p.measure_unit)),'unitCost',case when l.unit_cost is null then null else jsonb_build_object('amount',l.unit_cost::text,'currency','VES')end,'movementId',l.movement_id)order by l.id)from public.shared_inventory_operation_lines l join public.shared_inventory_products p on p.tenant_id=l.tenant_id and p.id=l.product_id where l.tenant_id=o.tenant_id and l.operation_id=o.id),'[]'::jsonb),
 'capabilities',jsonb_build_object('canPost',o.status='draft','canReverse',o.status='posted','canEditMetadata',o.status='draft'))from public.shared_inventory_operations o where o.tenant_id=p_tenant and o.id=p_operation_id
$$;

create or replace function public.list_native_inventory_flows(p_actor_user_id uuid,p_organization_id uuid,p_company_id text,p_from date,p_to date,p_direction text default null,p_reason text default null,p_source_kind text default null,p_product_id text default null,p_status text default null,p_search text default null,p_cursor text default null,p_limit integer default 25)returns jsonb language plpgsql stable security definer set search_path=public as $$
declare v_tenant uuid;v_offset integer:=0;v_items jsonb;v_total integer;v_value numeric;v_quantities jsonb;
begin v_tenant:=public.native_products_assert_access(p_actor_user_id,p_organization_id,p_company_id);if p_from>p_to or p_limit<1 or p_limit>100 then raise exception'INVENTORY_OPERATION_INVALID';end if;if p_cursor is not null then begin v_offset:=convert_from(decode(p_cursor,'base64'),'utf8')::integer;exception when others then raise exception'INVENTORY_OPERATION_INVALID';end;end if;
 with flows as(
  select m.id,coalesce(l.operation_id,m.id)operation_id,m.date effective_date,public.native_inventory_legacy_direction(m.type)direction,coalesce(o.reason,public.native_inventory_legacy_reason(m.type))reason,coalesce(o.status,'posted')status,p.id product_id,p.code,p.name,public.native_product_unit(p.measure_unit)unit,m.quantity,m.unit_cost,m.total_cost,coalesce(o.source_kind,case when m.purchase_invoice_id is not null then'purchasing'when m.type='salida'then'sales'else'migration'end)source_kind,coalesce(o.source_document_id,m.purchase_invoice_id,m.id)source_document_id,coalesce(o.reference,nullif(m.reference,''))reference,coalesce(o.notes,nullif(m.notes,''))notes,coalesce(o.posted_at,m.created_at)posted_at
  from public.shared_inventory_movements m join public.shared_inventory_products p on p.tenant_id=m.tenant_id and p.id=m.product_id left join public.shared_inventory_operation_lines l on l.tenant_id=m.tenant_id and l.movement_id=m.id left join public.shared_inventory_operations o on o.tenant_id=l.tenant_id and o.id=l.operation_id where m.tenant_id=v_tenant and m.company_id=p_company_id
  union all select l.id,o.id,o.effective_date,l.direction,o.reason,o.status,p.id,p.code,p.name,public.native_product_unit(p.measure_unit),l.quantity,l.unit_cost,null::numeric,o.source_kind,o.source_document_id,o.reference,o.notes,o.posted_at from public.shared_inventory_operations o join public.shared_inventory_operation_lines l on l.tenant_id=o.tenant_id and l.operation_id=o.id join public.shared_inventory_products p on p.tenant_id=l.tenant_id and p.id=l.product_id where o.tenant_id=v_tenant and o.company_id=p_company_id and l.movement_id is null
 ),filtered as(select*from flows where effective_date between p_from and p_to and(p_direction is null or direction=p_direction)and(p_reason is null or reason=p_reason)and(p_source_kind is null or source_kind=p_source_kind)and(p_product_id is null or product_id=p_product_id)and(p_status is null or status=p_status)and(p_search is null or name ilike'%'||p_search||'%'or code ilike'%'||p_search||'%'or coalesce(reference,'')ilike'%'||p_search||'%'))
 select count(*),coalesce(sum(abs(total_cost)),0),coalesce((select jsonb_agg(jsonb_build_object('unit',unit,'value',value::text)order by unit)from(select unit,sum(quantity)value from filtered group by unit)q),'[]')into v_total,v_value,v_quantities from filtered;
 with flows as(select m.id,coalesce(l.operation_id,m.id)operation_id,m.date effective_date,public.native_inventory_legacy_direction(m.type)direction,coalesce(o.reason,public.native_inventory_legacy_reason(m.type))reason,coalesce(o.status,'posted')status,p.id product_id,p.code,p.name,public.native_product_unit(p.measure_unit)unit,m.quantity,m.unit_cost,m.total_cost,coalesce(o.source_kind,case when m.purchase_invoice_id is not null then'purchasing'when m.type='salida'then'sales'else'migration'end)source_kind,coalesce(o.source_document_id,m.purchase_invoice_id,m.id)source_document_id,coalesce(o.reference,nullif(m.reference,''))reference,coalesce(o.notes,nullif(m.notes,''))notes,coalesce(o.posted_at,m.created_at)posted_at from public.shared_inventory_movements m join public.shared_inventory_products p on p.tenant_id=m.tenant_id and p.id=m.product_id left join public.shared_inventory_operation_lines l on l.tenant_id=m.tenant_id and l.movement_id=m.id left join public.shared_inventory_operations o on o.tenant_id=l.tenant_id and o.id=l.operation_id where m.tenant_id=v_tenant and m.company_id=p_company_id union all select l.id,o.id,o.effective_date,l.direction,o.reason,o.status,p.id,p.code,p.name,public.native_product_unit(p.measure_unit),l.quantity,l.unit_cost,null::numeric,o.source_kind,o.source_document_id,o.reference,o.notes,o.posted_at from public.shared_inventory_operations o join public.shared_inventory_operation_lines l on l.tenant_id=o.tenant_id and l.operation_id=o.id join public.shared_inventory_products p on p.tenant_id=l.tenant_id and p.id=l.product_id where o.tenant_id=v_tenant and o.company_id=p_company_id and l.movement_id is null),filtered as(select*from flows where effective_date between p_from and p_to and(p_direction is null or direction=p_direction)and(p_reason is null or reason=p_reason)and(p_source_kind is null or source_kind=p_source_kind)and(p_product_id is null or product_id=p_product_id)and(p_status is null or status=p_status)and(p_search is null or name ilike'%'||p_search||'%'or code ilike'%'||p_search||'%'or coalesce(reference,'')ilike'%'||p_search||'%'))
 select coalesce(jsonb_agg(jsonb_build_object('id',id,'operationId',operation_id,'effectiveDate',effective_date,'direction',direction,'reason',reason,'status',status,'product',jsonb_build_object('id',product_id,'sku',code,'name',name),'quantity',jsonb_build_object('value',quantity::text,'unit',unit),'unitCost',case when unit_cost is null then null else jsonb_build_object('amount',unit_cost::text,'currency','VES')end,'totalCost',case when total_cost is null then null else jsonb_build_object('amount',total_cost::text,'currency','VES')end,'source',jsonb_build_object('kind',source_kind,'documentId',source_document_id),'reference',reference,'notes',notes,'postedAt',posted_at)order by effective_date desc,operation_id desc,id desc),'[]')into v_items from(select*from filtered order by effective_date desc,operation_id desc,id desc offset v_offset limit p_limit)s;
 return jsonb_build_object('items',v_items,'nextCursor',case when v_offset+p_limit<v_total then encode(convert_to((v_offset+p_limit)::text,'utf8'),'base64')else null end,'total',v_total,'summary',jsonb_build_object('movementCount',v_total,'totalValue',jsonb_build_object('amount',v_value::text,'currency','VES'),'quantities',v_quantities));end$$;

create or replace function public.get_native_inventory_operation(p_actor_user_id uuid,p_organization_id uuid,p_company_id text,p_operation_id text)returns jsonb language plpgsql stable security definer set search_path=public as $$declare v_tenant uuid;v_result jsonb;begin v_tenant:=public.native_products_assert_access(p_actor_user_id,p_organization_id,p_company_id);select public.native_inventory_operation_json(v_tenant,p_operation_id)into v_result;if v_result is null then raise exception'INVENTORY_OPERATION_NOT_FOUND';end if;return v_result;end$$;
create or replace function public.create_native_inventory_operation(p_actor_user_id uuid,p_organization_id uuid,p_company_id text,p_reason text,p_effective_date date,p_reference text,p_notes text,p_lines jsonb)returns jsonb language plpgsql security definer set search_path=public as $$declare v_tenant uuid;v_id text:=gen_random_uuid()::text;v_line jsonb;v_product record;begin v_tenant:=public.native_products_assert_access(p_actor_user_id,p_organization_id,p_company_id);if p_reason not in('opening_balance','stock_count_adjustment','self_consumption')or jsonb_typeof(p_lines)<>'array'or jsonb_array_length(p_lines)<1 then raise exception'INVENTORY_OPERATION_INVALID';end if;insert into public.shared_inventory_operations(tenant_id,id,company_id,reason,effective_date,source_document_id,reference,notes,created_by)values(v_tenant,v_id,p_company_id,p_reason,p_effective_date,v_id,nullif(btrim(p_reference),''),nullif(btrim(p_notes),''),p_actor_user_id);for v_line in select*from jsonb_array_elements(p_lines)loop select id,public.native_product_unit(measure_unit)unit into v_product from public.shared_inventory_products where tenant_id=v_tenant and company_id=p_company_id and id=v_line->>'productId'and active;if not found or v_product.unit<>v_line->>'unit'or(v_line->>'quantity')::numeric<=0 then raise exception'INVENTORY_OPERATION_INVALID';end if;if(p_reason='opening_balance'and v_line->>'direction'<>'inbound')or(p_reason='self_consumption'and v_line->>'direction'<>'outbound')then raise exception'INVENTORY_OPERATION_INVALID';end if;insert into public.shared_inventory_operation_lines(tenant_id,operation_id,id,product_id,direction,quantity,unit,unit_cost)values(v_tenant,v_id,gen_random_uuid()::text,v_product.id,v_line->>'direction',(v_line->>'quantity')::numeric,v_product.unit,nullif(v_line->>'unitCost','')::numeric);end loop;return public.native_inventory_operation_json(v_tenant,v_id);end$$;
create or replace function public.post_native_inventory_operation(p_actor_user_id uuid,p_organization_id uuid,p_company_id text,p_operation_id text,p_expected_version integer)returns jsonb language plpgsql security definer set search_path=public as $$declare v_tenant uuid;o record;l record;v_movement jsonb;begin v_tenant:=public.native_products_assert_access(p_actor_user_id,p_organization_id,p_company_id);select*into o from public.shared_inventory_operations where tenant_id=v_tenant and company_id=p_company_id and id=p_operation_id for update;if not found then raise exception'INVENTORY_OPERATION_NOT_FOUND';end if;if o.version<>p_expected_version then raise exception'INVENTORY_OPERATION_VERSION_CONFLICT';end if;if o.status<>'draft'then raise exception'INVENTORY_OPERATION_TRANSITION_INVALID';end if;for l in select*from public.shared_inventory_operation_lines where tenant_id=v_tenant and operation_id=o.id order by id loop v_movement:=public.shared_inventory_movement_save(v_tenant,jsonb_build_object('empresa_id',p_company_id,'producto_id',l.product_id,'tipo',public.native_inventory_legacy_type(o.reason,l.direction),'fecha',o.effective_date,'cantidad',l.quantity,'costo_unitario',coalesce(l.unit_cost,0),'referencia',coalesce(o.reference,''),'notas',coalesce(o.notes,'')));update public.shared_inventory_operation_lines set movement_id=v_movement->>'id',unit_cost=coalesce((v_movement->>'unit_cost')::numeric,unit_cost)where tenant_id=v_tenant and id=l.id;end loop;update public.shared_inventory_operations set status='posted',posted_at=now(),version=version+1,updated_at=now()where tenant_id=v_tenant and id=o.id;return public.native_inventory_operation_json(v_tenant,o.id);end$$;
create or replace function public.reverse_native_inventory_operation(p_actor_user_id uuid,p_organization_id uuid,p_company_id text,p_operation_id text,p_expected_version integer,p_effective_date date,p_reason text)returns jsonb language plpgsql security definer set search_path=public as $$declare v_tenant uuid;o record;l record;v_reversal text:=gen_random_uuid()::text;v_movement jsonb;begin v_tenant:=public.native_products_assert_access(p_actor_user_id,p_organization_id,p_company_id);select*into o from public.shared_inventory_operations where tenant_id=v_tenant and company_id=p_company_id and id=p_operation_id for update;if not found then raise exception'INVENTORY_OPERATION_NOT_FOUND';end if;if o.version<>p_expected_version then raise exception'INVENTORY_OPERATION_VERSION_CONFLICT';end if;if o.status<>'posted'then raise exception'INVENTORY_OPERATION_TRANSITION_INVALID';end if;insert into public.shared_inventory_operations(tenant_id,id,company_id,reason,effective_date,status,source_kind,source_document_id,reference,notes,version,posted_at,reversal_of,created_by)values(v_tenant,v_reversal,p_company_id,'reversal',p_effective_date,'posted','inventory',p_operation_id,'Reversión',nullif(btrim(p_reason),''),1,now(),p_operation_id,p_actor_user_id);for l in select*from public.shared_inventory_operation_lines where tenant_id=v_tenant and operation_id=o.id order by id loop v_movement:=public.shared_inventory_movement_save(v_tenant,jsonb_build_object('empresa_id',p_company_id,'producto_id',l.product_id,'tipo',public.native_inventory_legacy_type('reversal',case when l.direction='inbound'then'outbound'else'inbound'end),'fecha',p_effective_date,'cantidad',l.quantity,'costo_unitario',coalesce(l.unit_cost,0),'referencia','Reversión '||p_operation_id,'notas',p_reason));insert into public.shared_inventory_operation_lines(tenant_id,operation_id,id,product_id,direction,quantity,unit,unit_cost,movement_id)values(v_tenant,v_reversal,gen_random_uuid()::text,l.product_id,case when l.direction='inbound'then'outbound'else'inbound'end,l.quantity,l.unit,l.unit_cost,v_movement->>'id');end loop;update public.shared_inventory_operations set status='reversed',reversed_by=v_reversal,version=version+1,updated_at=now()where tenant_id=v_tenant and id=o.id;return public.native_inventory_operation_json(v_tenant,o.id);end$$;

revoke all on function public.list_native_inventory_flows(uuid,uuid,text,date,date,text,text,text,text,text,text,text,integer),public.get_native_inventory_operation(uuid,uuid,text,text),public.create_native_inventory_operation(uuid,uuid,text,text,date,text,text,jsonb),public.post_native_inventory_operation(uuid,uuid,text,text,integer),public.reverse_native_inventory_operation(uuid,uuid,text,text,integer,date,text)from public,anon,authenticated;
grant execute on function public.list_native_inventory_flows(uuid,uuid,text,date,date,text,text,text,text,text,text,text,integer),public.get_native_inventory_operation(uuid,uuid,text,text),public.create_native_inventory_operation(uuid,uuid,text,text,date,text,text,jsonb),public.post_native_inventory_operation(uuid,uuid,text,text,integer),public.reverse_native_inventory_operation(uuid,uuid,text,text,integer,date,text)to service_role;
