-- Exact native Sales dashboard over the shared operational source of truth.
-- Module availability is organization-scoped; company rows only scope operational data.
-- Historical null bases followed the Web rule COALESCE(base_iva,total_linea).
update public.shared_inventory_sales_invoice_items set vat_base=line_total where vat_base is null;
alter table public.shared_inventory_sales_invoice_items alter column vat_base set not null;

create or replace function public.ensure_shared_sales_item_vat_base()returns trigger language plpgsql set search_path=public as $$
begin new.vat_base:=coalesce(new.vat_base,new.line_total);return new;end $$;
drop trigger if exists shared_sales_item_vat_base_required on public.shared_inventory_sales_invoice_items;
create trigger shared_sales_item_vat_base_required before insert or update of vat_base,line_total on public.shared_inventory_sales_invoice_items for each row execute function public.ensure_shared_sales_item_vat_base();

do $$ declare v_invalid bigint;begin
 select count(*) into v_invalid from public.shared_inventory_sales_invoices f where f.document_type='venta'and f.status='confirmada'and round(f.vat_amount,2)<>(select round(coalesce(sum(case i.vat_rate when'reducida_8'then i.vat_base*.08 when'general_16'then i.vat_base*.16 else 0 end),0),2)from public.shared_inventory_sales_invoice_items i where i.tenant_id=f.tenant_id and i.invoice_id=f.id);
 if v_invalid>0 then raise exception 'Cannot enable native Sales dashboard: % confirmed invoices have unreconciled VAT',v_invalid;end if;
end $$;

insert into public.module_capabilities(module_id,capability_code)select id,'sales.dashboard'from public.module_catalog where code='sales'on conflict do nothing;

create or replace function public.get_native_sales_dashboard_snapshot(p_actor_user_id uuid,p_organization_id uuid,p_company_id text,p_from date,p_to date,p_granularity text default'day',p_recent_limit integer default 5)returns jsonb language plpgsql stable security definer set search_path=public as $$
declare v_tenant uuid;v_allowed boolean;v_result jsonb;
begin
 if p_from is null or p_to is null or p_from>p_to or p_to-p_from>365 or p_granularity<>'day'or p_recent_limit<1 or p_recent_limit>100 then raise exception'SALES_DASHBOARD_INVALID';end if;
 select tenant_id into v_tenant from public.shared_companies where organization_id=p_organization_id and id=p_company_id;
 if v_tenant is null then raise exception'SALES_DASHBOARD_ACCESS_DENIED';end if;
 select exists(select 1 from public.organization_memberships where organization_id=p_organization_id and user_id=p_actor_user_id and status='active')or exists(select 1 from public.organization_delegation_member_assignments a join public.organization_delegations d on d.id=a.delegation_id join public.organization_delegation_scopes s on s.delegation_id=d.id and s.scope='sales'where a.user_id=p_actor_user_id and a.status='active'and d.client_organization_id=p_organization_id and d.status='active'and d.valid_from<=now()and(d.valid_until is null or d.valid_until>now()))into v_allowed;
 if not coalesce(v_allowed,false)then raise exception'SALES_DASHBOARD_ACCESS_DENIED';end if;
 with invoices as(select f.*,c.name customer_name,coalesce((select sum(i.vat_base)filter(where i.vat_rate in('reducida_8','general_16'))from public.shared_inventory_sales_invoice_items i where i.tenant_id=f.tenant_id and i.invoice_id=f.id),0)taxable_base from public.shared_inventory_sales_invoices f left join public.shared_inventory_customers c on c.tenant_id=f.tenant_id and c.id=f.customer_id where f.tenant_id=v_tenant and f.company_id=p_company_id and f.document_type='venta'and f.invoice_date between p_from and p_to),confirmed as(select*from invoices where status='confirmada'),totals as(select coalesce(sum(total),0)total,coalesce(sum(taxable_base),0)base,coalesce(sum(vat_amount),0)vat,count(*)::integer count from confirmed),days as(select generate_series(p_from,p_to,interval'1 day')::date date),daily as(select invoice_date date,sum(total)total,sum(taxable_base)base,sum(vat_amount)vat,count(*)::integer count from confirmed group by invoice_date)
 select jsonb_build_object('period',jsonb_build_object('from',p_from::text,'to',p_to::text,'granularity','day'),'summary',jsonb_build_object('confirmedInvoicedAmount',public.native_sales_ves((select total from totals)),'taxableBaseAmount',public.native_sales_ves((select base from totals)),'vatDebitAmount',public.native_sales_ves((select vat from totals)),'confirmedInvoiceCount',(select count from totals),'draftInvoiceCount',(select count(*)::integer from invoices where status='borrador'),'averageTicketAmount',public.native_sales_ves(case when(select count from totals)=0 then 0 else(select total from totals)/(select count from totals)end)),'charts',(select jsonb_agg(jsonb_build_object('date',d.date::text,'confirmedInvoicedAmount',public.native_sales_ves(coalesce(x.total,0)),'taxableBaseAmount',public.native_sales_ves(coalesce(x.base,0)),'vatDebitAmount',public.native_sales_ves(coalesce(x.vat,0)),'confirmedInvoiceCount',coalesce(x.count,0))order by d.date)from days d left join daily x on x.date=d.date),'recentConfirmedInvoices',coalesce((select jsonb_agg(public.native_sales_document(to_jsonb(x))order by x.invoice_date desc,x.id desc)from(select*from confirmed order by invoice_date desc,id desc limit p_recent_limit)x),'[]'::jsonb),'recentDraftInvoices',coalesce((select jsonb_agg(public.native_sales_document(to_jsonb(x))order by x.invoice_date desc,x.id desc)from(select*from invoices where status='borrador'order by invoice_date desc,id desc limit p_recent_limit)x),'[]'::jsonb),'generatedAt',now()::text)into v_result;return v_result;
end $$;

create or replace function public.native_sales_ves(p numeric)returns jsonb language sql immutable set search_path=public as $$select jsonb_build_object('amount',round(coalesce(p,0),2)::text,'currency','VES')$$;
create or replace function public.native_sales_document(p jsonb)returns jsonb language sql stable set search_path=public as $$select jsonb_build_object('id',p->>'id','sourceKind','legacy_sales_invoice','documentType','invoice','invoiceNumber',coalesce(nullif(p->>'invoice_number',''),p->>'id'),'customerName',p->>'customer_name','date',p->>'invoice_date','status',case p->>'status'when'confirmada'then'confirmed'else'draft'end,'salesChannel',coalesce(p->>'sales_channel','administrative'),'subtotal',public.native_sales_ves((p->>'subtotal')::numeric),'taxableBase',public.native_sales_ves((p->>'taxable_base')::numeric),'vatAmount',public.native_sales_ves((p->>'vat_amount')::numeric),'total',public.native_sales_ves((p->>'total')::numeric),'transactionCurrency',coalesce(p->>'currency_code','VES'),'sourceSubtotal',p->>'source_subtotal','sourceVatAmount',p->>'source_vat_amount','sourceTotal',p->>'source_total')$$;

revoke all on function public.get_native_sales_dashboard_snapshot(uuid,uuid,text,date,date,text,integer)from public,anon,authenticated;grant execute on function public.get_native_sales_dashboard_snapshot(uuid,uuid,text,date,date,text,integer)to service_role;
create index if not exists shared_sales_invoices_native_dashboard_idx on public.shared_inventory_sales_invoices(tenant_id,company_id,document_type,status,invoice_date desc,id desc);
