-- Payment orders record administrative intent only; they never execute a transfer.
create table public.shared_payment_orders (
 tenant_id uuid not null references public.tenants(id), id text not null check(length(trim(id)) between 1 and 128), company_id text not null,
 beneficiary text not null check(length(trim(beneficiary)) between 1 and 240), concept text not null check(length(trim(concept)) between 1 and 1000), amount numeric(28,8) not null check(amount>0), currency varchar(3) not null check(currency~'^[A-Z]{3}$'), due_date date, status text not null default 'draft' check(status in('draft','cancelled')), version integer not null default 1 check(version>0), created_at timestamptz not null default now(),updated_at timestamptz not null default now(), primary key(tenant_id,id), foreign key(tenant_id,company_id)references public.shared_companies(tenant_id,id)
);
alter table public.shared_payment_orders enable row level security;
revoke all on public.shared_payment_orders from public,anon,authenticated,service_role;
create trigger operational_audit_shared_payment_orders after insert or update or delete on public.shared_payment_orders for each row execute function public.append_operational_audit_trigger('payment_order','direct');

create or replace function public.payment_order_validate(p_id text,p_beneficiary text,p_concept text,p_amount numeric,p_currency text,p_due_date date) returns void language plpgsql immutable security definer set search_path=public as $$ begin
 if p_id is null or length(trim(p_id)) not between 1 and 128 or p_beneficiary is null or length(trim(p_beneficiary)) not between 1 and 240 or p_concept is null or length(trim(p_concept)) not between 1 and 1000 or p_currency is null or p_currency !~ '^[A-Z]{3}$' or p_amount is null or p_amount<=0 or p_amount in ('NaN'::numeric,'Infinity'::numeric,'-Infinity'::numeric) or scale(p_amount)>8 or length(trunc(p_amount)::text)>20 or p_due_date in ('infinity'::date,'-infinity'::date) then raise exception 'PAYMENT_ORDER_INVALID'; end if;
end $$;
create or replace function public.payment_order_json(p_tenant_id uuid,p_organization_id uuid,p_company_id text,p_id text) returns jsonb language sql stable security definer set search_path=public as $$
 select jsonb_build_object('id',o.id,'tenant_id',o.tenant_id,'organization_id',c.organization_id,'company_id',o.company_id,'beneficiary',o.beneficiary,'concept',o.concept,'amount',o.amount::text,'currency',o.currency,'due_date',o.due_date,'status',o.status,'version',o.version) from public.shared_payment_orders o join public.shared_companies c on c.tenant_id=o.tenant_id and c.id=o.company_id where o.tenant_id=p_tenant_id and c.organization_id=p_organization_id and o.company_id=p_company_id and o.id=p_id
$$;

create or replace function public.create_payment_order(p_actor_id uuid,p_organization_id uuid,p_company_id text,p_id text,p_beneficiary text,p_concept text,p_amount numeric,p_currency text,p_due_date date default null,p_branch_id text default null,p_device_id text default null) returns jsonb language plpgsql security definer set search_path=public as $$ declare v_tenant uuid; begin
 perform public.payment_order_validate(p_id,p_beneficiary,p_concept,p_amount,p_currency,p_due_date); v_tenant:=public.assert_user_security_access(p_actor_id,p_organization_id,p_company_id,'payment_orders.create'); perform public.set_operational_audit_context(p_actor_id,p_organization_id,p_company_id,p_branch_id,p_device_id);
 insert into public.shared_payment_orders(tenant_id,id,company_id,beneficiary,concept,amount,currency,due_date) values(v_tenant,trim(p_id),p_company_id,trim(p_beneficiary),trim(p_concept),p_amount,p_currency,p_due_date); return public.payment_order_json(v_tenant,p_organization_id,p_company_id,trim(p_id));
end $$;
create or replace function public.update_payment_order(p_actor_id uuid,p_organization_id uuid,p_company_id text,p_id text,p_expected_version integer,p_beneficiary text default null,p_concept text default null,p_amount numeric default null,p_currency text default null,p_due_date date default null,p_due_date_set boolean default false,p_branch_id text default null,p_device_id text default null) returns jsonb language plpgsql security definer set search_path=public as $$ declare v_tenant uuid; begin
 if p_expected_version is null or p_expected_version<1 or p_id is null or length(trim(p_id)) not between 1 and 128 or p_beneficiary is not null and length(trim(p_beneficiary)) not between 1 and 240 or p_concept is not null and length(trim(p_concept)) not between 1 and 1000 or p_currency is not null and p_currency !~ '^[A-Z]{3}$' or p_amount is not null and (p_amount<=0 or p_amount in ('NaN'::numeric,'Infinity'::numeric,'-Infinity'::numeric) or scale(p_amount)>8 or length(trunc(p_amount)::text)>20) or p_due_date_set and p_due_date in ('infinity'::date,'-infinity'::date) then raise exception 'PAYMENT_ORDER_INVALID'; end if;
 v_tenant:=public.assert_user_security_access(p_actor_id,p_organization_id,p_company_id,'payment_orders.update'); perform public.set_operational_audit_context(p_actor_id,p_organization_id,p_company_id,p_branch_id,p_device_id);
 update public.shared_payment_orders set beneficiary=coalesce(trim(p_beneficiary),beneficiary),concept=coalesce(trim(p_concept),concept),amount=coalesce(p_amount,amount),currency=coalesce(p_currency,currency),due_date=case when p_due_date_set then p_due_date else due_date end,version=version+1,updated_at=clock_timestamp() where tenant_id=v_tenant and company_id=p_company_id and id=trim(p_id) and status='draft' and version=p_expected_version;
 if not found then raise exception 'PAYMENT_ORDER_CONFLICT'; end if; return public.payment_order_json(v_tenant,p_organization_id,p_company_id,trim(p_id));
end $$;
create or replace function public.cancel_payment_order(p_actor_id uuid,p_organization_id uuid,p_company_id text,p_id text,p_expected_version integer,p_branch_id text default null,p_device_id text default null) returns jsonb language plpgsql security definer set search_path=public as $$ declare v_tenant uuid; begin
 if p_expected_version is null or p_expected_version<1 or p_id is null or length(trim(p_id)) not between 1 and 128 then raise exception 'PAYMENT_ORDER_INVALID'; end if; v_tenant:=public.assert_user_security_access(p_actor_id,p_organization_id,p_company_id,'payment_orders.void'); perform public.set_operational_audit_context(p_actor_id,p_organization_id,p_company_id,p_branch_id,p_device_id); update public.shared_payment_orders set status='cancelled',version=version+1,updated_at=clock_timestamp() where tenant_id=v_tenant and company_id=p_company_id and id=trim(p_id) and status='draft' and version=p_expected_version; if not found then raise exception 'PAYMENT_ORDER_CONFLICT'; end if; return public.payment_order_json(v_tenant,p_organization_id,p_company_id,trim(p_id));
end $$;
create or replace function public.delete_payment_order(p_actor_id uuid,p_organization_id uuid,p_company_id text,p_id text,p_expected_version integer,p_branch_id text default null,p_device_id text default null) returns void language plpgsql security definer set search_path=public as $$ declare v_tenant uuid; begin
 if p_expected_version is null or p_expected_version<1 or p_id is null or length(trim(p_id)) not between 1 and 128 then raise exception 'PAYMENT_ORDER_INVALID'; end if; v_tenant:=public.assert_user_security_access(p_actor_id,p_organization_id,p_company_id,'payment_orders.delete'); perform public.set_operational_audit_context(p_actor_id,p_organization_id,p_company_id,p_branch_id,p_device_id); delete from public.shared_payment_orders where tenant_id=v_tenant and company_id=p_company_id and id=trim(p_id) and status='draft' and version=p_expected_version; if not found then raise exception 'PAYMENT_ORDER_CONFLICT'; end if;
end $$;
create or replace function public.get_payment_order(p_actor_id uuid,p_organization_id uuid,p_company_id text,p_id text) returns jsonb language plpgsql security definer set search_path=public as $$ declare v_tenant uuid;v_result jsonb; begin
 if p_id is null or length(trim(p_id)) not between 1 and 128 then raise exception 'PAYMENT_ORDER_INVALID'; end if; v_tenant:=public.assert_user_security_access(p_actor_id,p_organization_id,p_company_id,'payment_orders.read'); v_result:=public.payment_order_json(v_tenant,p_organization_id,p_company_id,trim(p_id)); if v_result is null then raise exception 'PAYMENT_ORDER_NOT_FOUND'; end if; return v_result;
end $$;

insert into public.access_control_permissions(code,resource,action,description) values ('payment_orders.create','payment_orders','create','Crear órdenes de pago'),('payment_orders.update','payment_orders','update','Editar órdenes de pago'),('payment_orders.delete','payment_orders','delete','Eliminar órdenes de pago'),('payment_orders.void','payment_orders','void','Anular órdenes de pago'),('payment_orders.read','payment_orders','read','Ver órdenes de pago') on conflict(code) do update set resource=excluded.resource,action=excluded.action,description=excluded.description;
insert into public.organization_role_permissions(role_id,permission_code) select r.id,p.code from public.organization_roles r cross join(select unnest(array['payment_orders.create','payment_orders.update','payment_orders.delete','payment_orders.void','payment_orders.read']) code)p where r.code in('owner','admin') and r.status='active' on conflict do nothing;
revoke all on function public.payment_order_validate(text,text,text,numeric,text,date),public.payment_order_json(uuid,uuid,text,text),public.create_payment_order(uuid,uuid,text,text,text,text,numeric,text,date,text,text),public.update_payment_order(uuid,uuid,text,text,integer,text,text,numeric,text,date,boolean,text,text),public.cancel_payment_order(uuid,uuid,text,text,integer,text,text),public.delete_payment_order(uuid,uuid,text,text,integer,text,text),public.get_payment_order(uuid,uuid,text,text) from public,anon,authenticated,service_role;
grant execute on function public.create_payment_order(uuid,uuid,text,text,text,text,numeric,text,date,text,text),public.update_payment_order(uuid,uuid,text,text,integer,text,text,numeric,text,date,boolean,text,text),public.cancel_payment_order(uuid,uuid,text,text,integer,text,text),public.delete_payment_order(uuid,uuid,text,text,integer,text,text),public.get_payment_order(uuid,uuid,text,text) to service_role;
